// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paymentorder type in the database.
	Label = "payment_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTradeNo holds the string denoting the trade_no field in the database.
	FieldTradeNo = "trade_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPaymentAmount holds the string denoting the payment_amount field in the database.
	FieldPaymentAmount = "payment_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldExpiredAt holds the string denoting the expired_at field in the database.
	FieldExpiredAt = "expired_at"
	// FieldAlipayTradeNo holds the string denoting the alipay_trade_no field in the database.
	FieldAlipayTradeNo = "alipay_trade_no"
	// FieldAlipayTransLogID holds the string denoting the alipay_trans_log_id field in the database.
	FieldAlipayTransLogID = "alipay_trans_log_id"
	// FieldPayerAccount holds the string denoting the payer_account field in the database.
	FieldPayerAccount = "payer_account"
	// FieldCreditAmount holds the string denoting the credit_amount field in the database.
	FieldCreditAmount = "credit_amount"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the paymentorder in the database.
	Table = "payment_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "payment_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for paymentorder fields.
var Columns = []string{
	FieldID,
	FieldTradeNo,
	FieldUserID,
	FieldAmount,
	FieldPaymentAmount,
	FieldStatus,
	FieldCreatedAt,
	FieldPaidAt,
	FieldExpiredAt,
	FieldAlipayTradeNo,
	FieldAlipayTransLogID,
	FieldPayerAccount,
	FieldCreditAmount,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TradeNoValidator is a validator for the "trade_no" field. It is called by the builders before save.
	TradeNoValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(int64) error
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(float64) error
	// PaymentAmountValidator is a validator for the "payment_amount" field. It is called by the builders before save.
	PaymentAmountValidator func(float64) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// AlipayTradeNoValidator is a validator for the "alipay_trade_no" field. It is called by the builders before save.
	AlipayTradeNoValidator func(string) error
	// AlipayTransLogIDValidator is a validator for the "alipay_trans_log_id" field. It is called by the builders before save.
	AlipayTransLogIDValidator func(string) error
	// PayerAccountValidator is a validator for the "payer_account" field. It is called by the builders before save.
	PayerAccountValidator func(string) error
)

// OrderOption defines the ordering options for the PaymentOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTradeNo orders the results by the trade_no field.
func ByTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradeNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByPaymentAmount orders the results by the payment_amount field.
func ByPaymentAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByExpiredAt orders the results by the expired_at field.
func ByExpiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredAt, opts...).ToFunc()
}

// ByAlipayTradeNo orders the results by the alipay_trade_no field.
func ByAlipayTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlipayTradeNo, opts...).ToFunc()
}

// ByAlipayTransLogID orders the results by the alipay_trans_log_id field.
func ByAlipayTransLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlipayTransLogID, opts...).ToFunc()
}

// ByPayerAccount orders the results by the payer_account field.
func ByPayerAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayerAccount, opts...).ToFunc()
}

// ByCreditAmount orders the results by the credit_amount field.
func ByCreditAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditAmount, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
