// Code generated by ent, DO NOT EDIT.

package paymentorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldID, id))
}

// TradeNo applies equality check predicate on the "trade_no" field. It's identical to TradeNoEQ.
func TradeNo(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldTradeNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAmount, v))
}

// PaymentAmount applies equality check predicate on the "payment_amount" field. It's identical to PaymentAmountEQ.
func PaymentAmount(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaymentAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaidAt, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldExpiredAt, v))
}

// AlipayTradeNo applies equality check predicate on the "alipay_trade_no" field. It's identical to AlipayTradeNoEQ.
func AlipayTradeNo(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAlipayTradeNo, v))
}

// AlipayTransLogID applies equality check predicate on the "alipay_trans_log_id" field. It's identical to AlipayTransLogIDEQ.
func AlipayTransLogID(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAlipayTransLogID, v))
}

// PayerAccount applies equality check predicate on the "payer_account" field. It's identical to PayerAccountEQ.
func PayerAccount(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPayerAccount, v))
}

// CreditAmount applies equality check predicate on the "credit_amount" field. It's identical to CreditAmountEQ.
func CreditAmount(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreditAmount, v))
}

// RateCoefficient applies equality check predicate on the "rate_coefficient" field. It's identical to RateCoefficientEQ.
func RateCoefficient(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRateCoefficient, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldNotes, v))
}

// TradeNoEQ applies the EQ predicate on the "trade_no" field.
func TradeNoEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldTradeNo, v))
}

// TradeNoNEQ applies the NEQ predicate on the "trade_no" field.
func TradeNoNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldTradeNo, v))
}

// TradeNoIn applies the In predicate on the "trade_no" field.
func TradeNoIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldTradeNo, vs...))
}

// TradeNoNotIn applies the NotIn predicate on the "trade_no" field.
func TradeNoNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldTradeNo, vs...))
}

// TradeNoGT applies the GT predicate on the "trade_no" field.
func TradeNoGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldTradeNo, v))
}

// TradeNoGTE applies the GTE predicate on the "trade_no" field.
func TradeNoGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldTradeNo, v))
}

// TradeNoLT applies the LT predicate on the "trade_no" field.
func TradeNoLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldTradeNo, v))
}

// TradeNoLTE applies the LTE predicate on the "trade_no" field.
func TradeNoLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldTradeNo, v))
}

// TradeNoContains applies the Contains predicate on the "trade_no" field.
func TradeNoContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldTradeNo, v))
}

// TradeNoHasPrefix applies the HasPrefix predicate on the "trade_no" field.
func TradeNoHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldTradeNo, v))
}

// TradeNoHasSuffix applies the HasSuffix predicate on the "trade_no" field.
func TradeNoHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldTradeNo, v))
}

// TradeNoEqualFold applies the EqualFold predicate on the "trade_no" field.
func TradeNoEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldTradeNo, v))
}

// TradeNoContainsFold applies the ContainsFold predicate on the "trade_no" field.
func TradeNoContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldTradeNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldAmount, v))
}

// PaymentAmountEQ applies the EQ predicate on the "payment_amount" field.
func PaymentAmountEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaymentAmount, v))
}

// PaymentAmountNEQ applies the NEQ predicate on the "payment_amount" field.
func PaymentAmountNEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldPaymentAmount, v))
}

// PaymentAmountIn applies the In predicate on the "payment_amount" field.
func PaymentAmountIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldPaymentAmount, vs...))
}

// PaymentAmountNotIn applies the NotIn predicate on the "payment_amount" field.
func PaymentAmountNotIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldPaymentAmount, vs...))
}

// PaymentAmountGT applies the GT predicate on the "payment_amount" field.
func PaymentAmountGT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldPaymentAmount, v))
}

// PaymentAmountGTE applies the GTE predicate on the "payment_amount" field.
func PaymentAmountGTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldPaymentAmount, v))
}

// PaymentAmountLT applies the LT predicate on the "payment_amount" field.
func PaymentAmountLT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldPaymentAmount, v))
}

// PaymentAmountLTE applies the LTE predicate on the "payment_amount" field.
func PaymentAmountLTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldPaymentAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldPaidAt))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldExpiredAt, v))
}

// AlipayTradeNoEQ applies the EQ predicate on the "alipay_trade_no" field.
func AlipayTradeNoEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAlipayTradeNo, v))
}

// AlipayTradeNoNEQ applies the NEQ predicate on the "alipay_trade_no" field.
func AlipayTradeNoNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldAlipayTradeNo, v))
}

// AlipayTradeNoIn applies the In predicate on the "alipay_trade_no" field.
func AlipayTradeNoIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldAlipayTradeNo, vs...))
}

// AlipayTradeNoNotIn applies the NotIn predicate on the "alipay_trade_no" field.
func AlipayTradeNoNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldAlipayTradeNo, vs...))
}

// AlipayTradeNoGT applies the GT predicate on the "alipay_trade_no" field.
func AlipayTradeNoGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldAlipayTradeNo, v))
}

// AlipayTradeNoGTE applies the GTE predicate on the "alipay_trade_no" field.
func AlipayTradeNoGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldAlipayTradeNo, v))
}

// AlipayTradeNoLT applies the LT predicate on the "alipay_trade_no" field.
func AlipayTradeNoLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldAlipayTradeNo, v))
}

// AlipayTradeNoLTE applies the LTE predicate on the "alipay_trade_no" field.
func AlipayTradeNoLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldAlipayTradeNo, v))
}

// AlipayTradeNoContains applies the Contains predicate on the "alipay_trade_no" field.
func AlipayTradeNoContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldAlipayTradeNo, v))
}

// AlipayTradeNoHasPrefix applies the HasPrefix predicate on the "alipay_trade_no" field.
func AlipayTradeNoHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldAlipayTradeNo, v))
}

// AlipayTradeNoHasSuffix applies the HasSuffix predicate on the "alipay_trade_no" field.
func AlipayTradeNoHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldAlipayTradeNo, v))
}

// AlipayTradeNoIsNil applies the IsNil predicate on the "alipay_trade_no" field.
func AlipayTradeNoIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldAlipayTradeNo))
}

// AlipayTradeNoNotNil applies the NotNil predicate on the "alipay_trade_no" field.
func AlipayTradeNoNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldAlipayTradeNo))
}

// AlipayTradeNoEqualFold applies the EqualFold predicate on the "alipay_trade_no" field.
func AlipayTradeNoEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldAlipayTradeNo, v))
}

// AlipayTradeNoContainsFold applies the ContainsFold predicate on the "alipay_trade_no" field.
func AlipayTradeNoContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldAlipayTradeNo, v))
}

// AlipayTransLogIDEQ applies the EQ predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDNEQ applies the NEQ predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDIn applies the In predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldAlipayTransLogID, vs...))
}

// AlipayTransLogIDNotIn applies the NotIn predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldAlipayTransLogID, vs...))
}

// AlipayTransLogIDGT applies the GT predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDGTE applies the GTE predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDLT applies the LT predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDLTE applies the LTE predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDContains applies the Contains predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDHasPrefix applies the HasPrefix predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDHasSuffix applies the HasSuffix predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDIsNil applies the IsNil predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldAlipayTransLogID))
}

// AlipayTransLogIDNotNil applies the NotNil predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldAlipayTransLogID))
}

// AlipayTransLogIDEqualFold applies the EqualFold predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldAlipayTransLogID, v))
}

// AlipayTransLogIDContainsFold applies the ContainsFold predicate on the "alipay_trans_log_id" field.
func AlipayTransLogIDContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldAlipayTransLogID, v))
}

// PayerAccountEQ applies the EQ predicate on the "payer_account" field.
func PayerAccountEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldPayerAccount, v))
}

// PayerAccountNEQ applies the NEQ predicate on the "payer_account" field.
func PayerAccountNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldPayerAccount, v))
}

// PayerAccountIn applies the In predicate on the "payer_account" field.
func PayerAccountIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldPayerAccount, vs...))
}

// PayerAccountNotIn applies the NotIn predicate on the "payer_account" field.
func PayerAccountNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldPayerAccount, vs...))
}

// PayerAccountGT applies the GT predicate on the "payer_account" field.
func PayerAccountGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldPayerAccount, v))
}

// PayerAccountGTE applies the GTE predicate on the "payer_account" field.
func PayerAccountGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldPayerAccount, v))
}

// PayerAccountLT applies the LT predicate on the "payer_account" field.
func PayerAccountLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldPayerAccount, v))
}

// PayerAccountLTE applies the LTE predicate on the "payer_account" field.
func PayerAccountLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldPayerAccount, v))
}

// PayerAccountContains applies the Contains predicate on the "payer_account" field.
func PayerAccountContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldPayerAccount, v))
}

// PayerAccountHasPrefix applies the HasPrefix predicate on the "payer_account" field.
func PayerAccountHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldPayerAccount, v))
}

// PayerAccountHasSuffix applies the HasSuffix predicate on the "payer_account" field.
func PayerAccountHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldPayerAccount, v))
}

// PayerAccountIsNil applies the IsNil predicate on the "payer_account" field.
func PayerAccountIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldPayerAccount))
}

// PayerAccountNotNil applies the NotNil predicate on the "payer_account" field.
func PayerAccountNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldPayerAccount))
}

// PayerAccountEqualFold applies the EqualFold predicate on the "payer_account" field.
func PayerAccountEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldPayerAccount, v))
}

// PayerAccountContainsFold applies the ContainsFold predicate on the "payer_account" field.
func PayerAccountContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldPayerAccount, v))
}

// CreditAmountEQ applies the EQ predicate on the "credit_amount" field.
func CreditAmountEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "credit_amount" field.
func CreditAmountNEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "credit_amount" field.
func CreditAmountIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "credit_amount" field.
func CreditAmountNotIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "credit_amount" field.
func CreditAmountGT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "credit_amount" field.
func CreditAmountGTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "credit_amount" field.
func CreditAmountLT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "credit_amount" field.
func CreditAmountLTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldCreditAmount, v))
}

// CreditAmountIsNil applies the IsNil predicate on the "credit_amount" field.
func CreditAmountIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldCreditAmount))
}

// CreditAmountNotNil applies the NotNil predicate on the "credit_amount" field.
func CreditAmountNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldCreditAmount))
}

// RateCoefficientEQ applies the EQ predicate on the "rate_coefficient" field.
func RateCoefficientEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldRateCoefficient, v))
}

// RateCoefficientNEQ applies the NEQ predicate on the "rate_coefficient" field.
func RateCoefficientNEQ(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldRateCoefficient, v))
}

// RateCoefficientIn applies the In predicate on the "rate_coefficient" field.
func RateCoefficientIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldRateCoefficient, vs...))
}

// RateCoefficientNotIn applies the NotIn predicate on the "rate_coefficient" field.
func RateCoefficientNotIn(vs ...float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldRateCoefficient, vs...))
}

// RateCoefficientGT applies the GT predicate on the "rate_coefficient" field.
func RateCoefficientGT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldRateCoefficient, v))
}

// RateCoefficientGTE applies the GTE predicate on the "rate_coefficient" field.
func RateCoefficientGTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldRateCoefficient, v))
}

// RateCoefficientLT applies the LT predicate on the "rate_coefficient" field.
func RateCoefficientLT(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldRateCoefficient, v))
}

// RateCoefficientLTE applies the LTE predicate on the "rate_coefficient" field.
func RateCoefficientLTE(v float64) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldRateCoefficient, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.FieldContainsFold(FieldNotes, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PaymentOrder {
	return predicate.PaymentOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PaymentOrder {
	return predicate.PaymentOrder(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentOrder) predicate.PaymentOrder {
	return predicate.PaymentOrder(sql.NotPredicates(p))
}
