// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshotdaily"
)

// BalanceSnapshotDaily is the model entity for the BalanceSnapshotDaily schema.
type BalanceSnapshotDaily struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SnapshotDate holds the value of the "snapshot_date" field.
	SnapshotDate time.Time `json:"snapshot_date,omitempty"`
	// TotalBalance holds the value of the "total_balance" field.
	TotalBalance float64 `json:"total_balance,omitempty"`
	// UserCount holds the value of the "user_count" field.
	UserCount int64 `json:"user_count,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt   time.Time `json:"computed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceSnapshotDaily) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancesnapshotdaily.FieldTotalBalance:
			values[i] = new(sql.NullFloat64)
		case balancesnapshotdaily.FieldID, balancesnapshotdaily.FieldUserCount:
			values[i] = new(sql.NullInt64)
		case balancesnapshotdaily.FieldSnapshotDate, balancesnapshotdaily.FieldComputedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceSnapshotDaily fields.
func (_m *BalanceSnapshotDaily) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancesnapshotdaily.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balancesnapshotdaily.FieldSnapshotDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_date", values[i])
			} else if value.Valid {
				_m.SnapshotDate = value.Time
			}
		case balancesnapshotdaily.FieldTotalBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_balance", values[i])
			} else if value.Valid {
				_m.TotalBalance = value.Float64
			}
		case balancesnapshotdaily.FieldUserCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_count", values[i])
			} else if value.Valid {
				_m.UserCount = value.Int64
			}
		case balancesnapshotdaily.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceSnapshotDaily.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceSnapshotDaily) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BalanceSnapshotDaily.
// Note that you need to call BalanceSnapshotDaily.Unwrap() before calling this method if this BalanceSnapshotDaily
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceSnapshotDaily) Update() *BalanceSnapshotDailyUpdateOne {
	return NewBalanceSnapshotDailyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceSnapshotDaily entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceSnapshotDaily) Unwrap() *BalanceSnapshotDaily {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceSnapshotDaily is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceSnapshotDaily) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceSnapshotDaily(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("snapshot_date=")
	builder.WriteString(_m.SnapshotDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("total_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalBalance))
	builder.WriteString(", ")
	builder.WriteString("user_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserCount))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BalanceSnapshotDailies is a parsable slice of BalanceSnapshotDaily.
type BalanceSnapshotDailies []*BalanceSnapshotDaily
