// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshotdaily"
)

// BalanceSnapshotDailyCreate is the builder for creating a BalanceSnapshotDaily entity.
type BalanceSnapshotDailyCreate struct {
	config
	mutation *BalanceSnapshotDailyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_c *BalanceSnapshotDailyCreate) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyCreate {
	_c.mutation.SetSnapshotDate(v)
	return _c
}

// SetTotalBalance sets the "total_balance" field.
func (_c *BalanceSnapshotDailyCreate) SetTotalBalance(v float64) *BalanceSnapshotDailyCreate {
	_c.mutation.SetTotalBalance(v)
	return _c
}

// SetNillableTotalBalance sets the "total_balance" field if the given value is not nil.
func (_c *BalanceSnapshotDailyCreate) SetNillableTotalBalance(v *float64) *BalanceSnapshotDailyCreate {
	if v != nil {
		_c.SetTotalBalance(*v)
	}
	return _c
}

// SetUserCount sets the "user_count" field.
func (_c *BalanceSnapshotDailyCreate) SetUserCount(v int64) *BalanceSnapshotDailyCreate {
	_c.mutation.SetUserCount(v)
	return _c
}

// SetNillableUserCount sets the "user_count" field if the given value is not nil.
func (_c *BalanceSnapshotDailyCreate) SetNillableUserCount(v *int64) *BalanceSnapshotDailyCreate {
	if v != nil {
		_c.SetUserCount(*v)
	}
	return _c
}

// SetComputedAt sets the "computed_at" field.
func (_c *BalanceSnapshotDailyCreate) SetComputedAt(v time.Time) *BalanceSnapshotDailyCreate {
	_c.mutation.SetComputedAt(v)
	return _c
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_c *BalanceSnapshotDailyCreate) SetNillableComputedAt(v *time.Time) *BalanceSnapshotDailyCreate {
	if v != nil {
		_c.SetComputedAt(*v)
	}
	return _c
}

// Mutation returns the BalanceSnapshotDailyMutation object of the builder.
func (_c *BalanceSnapshotDailyCreate) Mutation() *BalanceSnapshotDailyMutation {
	return _c.mutation
}

// Save creates the BalanceSnapshotDaily in the database.
func (_c *BalanceSnapshotDailyCreate) Save(ctx context.Context) (*BalanceSnapshotDaily, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceSnapshotDailyCreate) SaveX(ctx context.Context) *BalanceSnapshotDaily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSnapshotDailyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSnapshotDailyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceSnapshotDailyCreate) defaults() {
	if _, ok := _c.mutation.TotalBalance(); !ok {
		v := balancesnapshotdaily.DefaultTotalBalance
		_c.mutation.SetTotalBalance(v)
	}
	if _, ok := _c.mutation.UserCount(); !ok {
		v := balancesnapshotdaily.DefaultUserCount
		_c.mutation.SetUserCount(v)
	}
	if _, ok := _c.mutation.ComputedAt(); !ok {
		v := balancesnapshotdaily.DefaultComputedAt()
		_c.mutation.SetComputedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceSnapshotDailyCreate) check() error {
	if _, ok := _c.mutation.SnapshotDate(); !ok {
		return &ValidationError{Name: "snapshot_date", err: errors.New(`ent: missing required field "BalanceSnapshotDaily.snapshot_date"`)}
	}
	if _, ok := _c.mutation.TotalBalance(); !ok {
		return &ValidationError{Name: "total_balance", err: errors.New(`ent: missing required field "BalanceSnapshotDaily.total_balance"`)}
	}
	if _, ok := _c.mutation.UserCount(); !ok {
		return &ValidationError{Name: "user_count", err: errors.New(`ent: missing required field "BalanceSnapshotDaily.user_count"`)}
	}
	if _, ok := _c.mutation.ComputedAt(); !ok {
		return &ValidationError{Name: "computed_at", err: errors.New(`ent: missing required field "BalanceSnapshotDaily.computed_at"`)}
	}
	return nil
}

func (_c *BalanceSnapshotDailyCreate) sqlSave(ctx context.Context) (*BalanceSnapshotDaily, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceSnapshotDailyCreate) createSpec() (*BalanceSnapshotDaily, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceSnapshotDaily{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancesnapshotdaily.Table, sqlgraph.NewFieldSpec(balancesnapshotdaily.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SnapshotDate(); ok {
		_spec.SetField(balancesnapshotdaily.FieldSnapshotDate, field.TypeTime, value)
		_node.SnapshotDate = value
	}
	if value, ok := _c.mutation.TotalBalance(); ok {
		_spec.SetField(balancesnapshotdaily.FieldTotalBalance, field.TypeFloat64, value)
		_node.TotalBalance = value
	}
	if value, ok := _c.mutation.UserCount(); ok {
		_spec.SetField(balancesnapshotdaily.FieldUserCount, field.TypeInt64, value)
		_node.UserCount = value
	}
	if value, ok := _c.mutation.ComputedAt(); ok {
		_spec.SetField(balancesnapshotdaily.FieldComputedAt, field.TypeTime, value)
		_node.ComputedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSnapshotDaily.Create().
//		SetSnapshotDate(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSnapshotDailyUpsert) {
//			SetSnapshotDate(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSnapshotDailyCreate) OnConflict(opts ...sql.ConflictOption) *BalanceSnapshotDailyUpsertOne {
	_c.conflict = opts
	return &BalanceSnapshotDailyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSnapshotDailyCreate) OnConflictColumns(columns ...string) *BalanceSnapshotDailyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSnapshotDailyUpsertOne{
		create: _c,
	}
}

type (
	// BalanceSnapshotDailyUpsertOne is the builder for "upsert"-ing
	//  one BalanceSnapshotDaily node.
	BalanceSnapshotDailyUpsertOne struct {
		create *BalanceSnapshotDailyCreate
	}

	// BalanceSnapshotDailyUpsert is the "OnConflict" setter.
	BalanceSnapshotDailyUpsert struct {
		*sql.UpdateSet
	}
)

// SetSnapshotDate sets the "snapshot_date" field.
func (u *BalanceSnapshotDailyUpsert) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyUpsert {
	u.Set(balancesnapshotdaily.FieldSnapshotDate, v)
	return u
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsert) UpdateSnapshotDate() *BalanceSnapshotDailyUpsert {
	u.SetExcluded(balancesnapshotdaily.FieldSnapshotDate)
	return u
}

// SetTotalBalance sets the "total_balance" field.
func (u *BalanceSnapshotDailyUpsert) SetTotalBalance(v float64) *BalanceSnapshotDailyUpsert {
	u.Set(balancesnapshotdaily.FieldTotalBalance, v)
	return u
}

// UpdateTotalBalance sets the "total_balance" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsert) UpdateTotalBalance() *BalanceSnapshotDailyUpsert {
	u.SetExcluded(balancesnapshotdaily.FieldTotalBalance)
	return u
}

// AddTotalBalance adds v to the "total_balance" field.
func (u *BalanceSnapshotDailyUpsert) AddTotalBalance(v float64) *BalanceSnapshotDailyUpsert {
	u.Add(balancesnapshotdaily.FieldTotalBalance, v)
	return u
}

// SetUserCount sets the "user_count" field.
func (u *BalanceSnapshotDailyUpsert) SetUserCount(v int64) *BalanceSnapshotDailyUpsert {
	u.Set(balancesnapshotdaily.FieldUserCount, v)
	return u
}

// UpdateUserCount sets the "user_count" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsert) UpdateUserCount() *BalanceSnapshotDailyUpsert {
	u.SetExcluded(balancesnapshotdaily.FieldUserCount)
	return u
}

// AddUserCount adds v to the "user_count" field.
func (u *BalanceSnapshotDailyUpsert) AddUserCount(v int64) *BalanceSnapshotDailyUpsert {
	u.Add(balancesnapshotdaily.FieldUserCount, v)
	return u
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotDailyUpsert) SetComputedAt(v time.Time) *BalanceSnapshotDailyUpsert {
	u.Set(balancesnapshotdaily.FieldComputedAt, v)
	return u
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsert) UpdateComputedAt() *BalanceSnapshotDailyUpsert {
	u.SetExcluded(balancesnapshotdaily.FieldComputedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSnapshotDailyUpsertOne) UpdateNewValues() *BalanceSnapshotDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceSnapshotDailyUpsertOne) Ignore() *BalanceSnapshotDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSnapshotDailyUpsertOne) DoNothing() *BalanceSnapshotDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSnapshotDailyCreate.OnConflict
// documentation for more info.
func (u *BalanceSnapshotDailyUpsertOne) Update(set func(*BalanceSnapshotDailyUpsert)) *BalanceSnapshotDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSnapshotDailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (u *BalanceSnapshotDailyUpsertOne) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetSnapshotDate(v)
	})
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertOne) UpdateSnapshotDate() *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateSnapshotDate()
	})
}

// SetTotalBalance sets the "total_balance" field.
func (u *BalanceSnapshotDailyUpsertOne) SetTotalBalance(v float64) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetTotalBalance(v)
	})
}

// AddTotalBalance adds v to the "total_balance" field.
func (u *BalanceSnapshotDailyUpsertOne) AddTotalBalance(v float64) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.AddTotalBalance(v)
	})
}

// UpdateTotalBalance sets the "total_balance" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertOne) UpdateTotalBalance() *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateTotalBalance()
	})
}

// SetUserCount sets the "user_count" field.
func (u *BalanceSnapshotDailyUpsertOne) SetUserCount(v int64) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetUserCount(v)
	})
}

// AddUserCount adds v to the "user_count" field.
func (u *BalanceSnapshotDailyUpsertOne) AddUserCount(v int64) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.AddUserCount(v)
	})
}

// UpdateUserCount sets the "user_count" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertOne) UpdateUserCount() *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateUserCount()
	})
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotDailyUpsertOne) SetComputedAt(v time.Time) *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetComputedAt(v)
	})
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertOne) UpdateComputedAt() *BalanceSnapshotDailyUpsertOne {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateComputedAt()
	})
}

// Exec executes the query.
func (u *BalanceSnapshotDailyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSnapshotDailyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSnapshotDailyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceSnapshotDailyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceSnapshotDailyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceSnapshotDailyCreateBulk is the builder for creating many BalanceSnapshotDaily entities in bulk.
type BalanceSnapshotDailyCreateBulk struct {
	config
	err      error
	builders []*BalanceSnapshotDailyCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceSnapshotDaily entities in the database.
func (_c *BalanceSnapshotDailyCreateBulk) Save(ctx context.Context) ([]*BalanceSnapshotDaily, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceSnapshotDaily, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceSnapshotDailyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceSnapshotDailyCreateBulk) SaveX(ctx context.Context) []*BalanceSnapshotDaily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceSnapshotDailyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceSnapshotDailyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceSnapshotDaily.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceSnapshotDailyUpsert) {
//			SetSnapshotDate(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceSnapshotDailyCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceSnapshotDailyUpsertBulk {
	_c.conflict = opts
	return &BalanceSnapshotDailyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceSnapshotDailyCreateBulk) OnConflictColumns(columns ...string) *BalanceSnapshotDailyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceSnapshotDailyUpsertBulk{
		create: _c,
	}
}

// BalanceSnapshotDailyUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceSnapshotDaily nodes.
type BalanceSnapshotDailyUpsertBulk struct {
	create *BalanceSnapshotDailyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceSnapshotDailyUpsertBulk) UpdateNewValues() *BalanceSnapshotDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceSnapshotDaily.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceSnapshotDailyUpsertBulk) Ignore() *BalanceSnapshotDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceSnapshotDailyUpsertBulk) DoNothing() *BalanceSnapshotDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceSnapshotDailyCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceSnapshotDailyUpsertBulk) Update(set func(*BalanceSnapshotDailyUpsert)) *BalanceSnapshotDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceSnapshotDailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (u *BalanceSnapshotDailyUpsertBulk) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetSnapshotDate(v)
	})
}

// UpdateSnapshotDate sets the "snapshot_date" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertBulk) UpdateSnapshotDate() *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateSnapshotDate()
	})
}

// SetTotalBalance sets the "total_balance" field.
func (u *BalanceSnapshotDailyUpsertBulk) SetTotalBalance(v float64) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetTotalBalance(v)
	})
}

// AddTotalBalance adds v to the "total_balance" field.
func (u *BalanceSnapshotDailyUpsertBulk) AddTotalBalance(v float64) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.AddTotalBalance(v)
	})
}

// UpdateTotalBalance sets the "total_balance" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertBulk) UpdateTotalBalance() *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateTotalBalance()
	})
}

// SetUserCount sets the "user_count" field.
func (u *BalanceSnapshotDailyUpsertBulk) SetUserCount(v int64) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetUserCount(v)
	})
}

// AddUserCount adds v to the "user_count" field.
func (u *BalanceSnapshotDailyUpsertBulk) AddUserCount(v int64) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.AddUserCount(v)
	})
}

// UpdateUserCount sets the "user_count" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertBulk) UpdateUserCount() *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateUserCount()
	})
}

// SetComputedAt sets the "computed_at" field.
func (u *BalanceSnapshotDailyUpsertBulk) SetComputedAt(v time.Time) *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.SetComputedAt(v)
	})
}

// UpdateComputedAt sets the "computed_at" field to the value that was provided on create.
func (u *BalanceSnapshotDailyUpsertBulk) UpdateComputedAt() *BalanceSnapshotDailyUpsertBulk {
	return u.Update(func(s *BalanceSnapshotDailyUpsert) {
		s.UpdateComputedAt()
	})
}

// Exec executes the query.
func (u *BalanceSnapshotDailyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceSnapshotDailyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceSnapshotDailyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceSnapshotDailyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
