// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshotdaily"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceSnapshotDailyUpdate is the builder for updating BalanceSnapshotDaily entities.
type BalanceSnapshotDailyUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceSnapshotDailyMutation
}

// Where appends a list predicates to the BalanceSnapshotDailyUpdate builder.
func (_u *BalanceSnapshotDailyUpdate) Where(ps ...predicate.BalanceSnapshotDaily) *BalanceSnapshotDailyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_u *BalanceSnapshotDailyUpdate) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyUpdate {
	_u.mutation.SetSnapshotDate(v)
	return _u
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdate) SetNillableSnapshotDate(v *time.Time) *BalanceSnapshotDailyUpdate {
	if v != nil {
		_u.SetSnapshotDate(*v)
	}
	return _u
}

// SetTotalBalance sets the "total_balance" field.
func (_u *BalanceSnapshotDailyUpdate) SetTotalBalance(v float64) *BalanceSnapshotDailyUpdate {
	_u.mutation.ResetTotalBalance()
	_u.mutation.SetTotalBalance(v)
	return _u
}

// SetNillableTotalBalance sets the "total_balance" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdate) SetNillableTotalBalance(v *float64) *BalanceSnapshotDailyUpdate {
	if v != nil {
		_u.SetTotalBalance(*v)
	}
	return _u
}

// AddTotalBalance adds value to the "total_balance" field.
func (_u *BalanceSnapshotDailyUpdate) AddTotalBalance(v float64) *BalanceSnapshotDailyUpdate {
	_u.mutation.AddTotalBalance(v)
	return _u
}

// SetUserCount sets the "user_count" field.
func (_u *BalanceSnapshotDailyUpdate) SetUserCount(v int64) *BalanceSnapshotDailyUpdate {
	_u.mutation.ResetUserCount()
	_u.mutation.SetUserCount(v)
	return _u
}

// SetNillableUserCount sets the "user_count" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdate) SetNillableUserCount(v *int64) *BalanceSnapshotDailyUpdate {
	if v != nil {
		_u.SetUserCount(*v)
	}
	return _u
}

// AddUserCount adds value to the "user_count" field.
func (_u *BalanceSnapshotDailyUpdate) AddUserCount(v int64) *BalanceSnapshotDailyUpdate {
	_u.mutation.AddUserCount(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *BalanceSnapshotDailyUpdate) SetComputedAt(v time.Time) *BalanceSnapshotDailyUpdate {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdate) SetNillableComputedAt(v *time.Time) *BalanceSnapshotDailyUpdate {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// Mutation returns the BalanceSnapshotDailyMutation object of the builder.
func (_u *BalanceSnapshotDailyUpdate) Mutation() *BalanceSnapshotDailyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceSnapshotDailyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceSnapshotDailyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceSnapshotDailyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceSnapshotDailyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BalanceSnapshotDailyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(balancesnapshotdaily.Table, balancesnapshotdaily.Columns, sqlgraph.NewFieldSpec(balancesnapshotdaily.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SnapshotDate(); ok {
		_spec.SetField(balancesnapshotdaily.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalBalance(); ok {
		_spec.SetField(balancesnapshotdaily.FieldTotalBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalBalance(); ok {
		_spec.AddField(balancesnapshotdaily.FieldTotalBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserCount(); ok {
		_spec.SetField(balancesnapshotdaily.FieldUserCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserCount(); ok {
		_spec.AddField(balancesnapshotdaily.FieldUserCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(balancesnapshotdaily.FieldComputedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancesnapshotdaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceSnapshotDailyUpdateOne is the builder for updating a single BalanceSnapshotDaily entity.
type BalanceSnapshotDailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceSnapshotDailyMutation
}

// SetSnapshotDate sets the "snapshot_date" field.
func (_u *BalanceSnapshotDailyUpdateOne) SetSnapshotDate(v time.Time) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.SetSnapshotDate(v)
	return _u
}

// SetNillableSnapshotDate sets the "snapshot_date" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdateOne) SetNillableSnapshotDate(v *time.Time) *BalanceSnapshotDailyUpdateOne {
	if v != nil {
		_u.SetSnapshotDate(*v)
	}
	return _u
}

// SetTotalBalance sets the "total_balance" field.
func (_u *BalanceSnapshotDailyUpdateOne) SetTotalBalance(v float64) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.ResetTotalBalance()
	_u.mutation.SetTotalBalance(v)
	return _u
}

// SetNillableTotalBalance sets the "total_balance" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdateOne) SetNillableTotalBalance(v *float64) *BalanceSnapshotDailyUpdateOne {
	if v != nil {
		_u.SetTotalBalance(*v)
	}
	return _u
}

// AddTotalBalance adds value to the "total_balance" field.
func (_u *BalanceSnapshotDailyUpdateOne) AddTotalBalance(v float64) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.AddTotalBalance(v)
	return _u
}

// SetUserCount sets the "user_count" field.
func (_u *BalanceSnapshotDailyUpdateOne) SetUserCount(v int64) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.ResetUserCount()
	_u.mutation.SetUserCount(v)
	return _u
}

// SetNillableUserCount sets the "user_count" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdateOne) SetNillableUserCount(v *int64) *BalanceSnapshotDailyUpdateOne {
	if v != nil {
		_u.SetUserCount(*v)
	}
	return _u
}

// AddUserCount adds value to the "user_count" field.
func (_u *BalanceSnapshotDailyUpdateOne) AddUserCount(v int64) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.AddUserCount(v)
	return _u
}

// SetComputedAt sets the "computed_at" field.
func (_u *BalanceSnapshotDailyUpdateOne) SetComputedAt(v time.Time) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.SetComputedAt(v)
	return _u
}

// SetNillableComputedAt sets the "computed_at" field if the given value is not nil.
func (_u *BalanceSnapshotDailyUpdateOne) SetNillableComputedAt(v *time.Time) *BalanceSnapshotDailyUpdateOne {
	if v != nil {
		_u.SetComputedAt(*v)
	}
	return _u
}

// Mutation returns the BalanceSnapshotDailyMutation object of the builder.
func (_u *BalanceSnapshotDailyUpdateOne) Mutation() *BalanceSnapshotDailyMutation {
	return _u.mutation
}

// Where appends a list predicates to the BalanceSnapshotDailyUpdate builder.
func (_u *BalanceSnapshotDailyUpdateOne) Where(ps ...predicate.BalanceSnapshotDaily) *BalanceSnapshotDailyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceSnapshotDailyUpdateOne) Select(field string, fields ...string) *BalanceSnapshotDailyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceSnapshotDaily entity.
func (_u *BalanceSnapshotDailyUpdateOne) Save(ctx context.Context) (*BalanceSnapshotDaily, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceSnapshotDailyUpdateOne) SaveX(ctx context.Context) *BalanceSnapshotDaily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceSnapshotDailyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceSnapshotDailyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BalanceSnapshotDailyUpdateOne) sqlSave(ctx context.Context) (_node *BalanceSnapshotDaily, err error) {
	_spec := sqlgraph.NewUpdateSpec(balancesnapshotdaily.Table, balancesnapshotdaily.Columns, sqlgraph.NewFieldSpec(balancesnapshotdaily.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceSnapshotDaily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancesnapshotdaily.FieldID)
		for _, f := range fields {
			if !balancesnapshotdaily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancesnapshotdaily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SnapshotDate(); ok {
		_spec.SetField(balancesnapshotdaily.FieldSnapshotDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalBalance(); ok {
		_spec.SetField(balancesnapshotdaily.FieldTotalBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalBalance(); ok {
		_spec.AddField(balancesnapshotdaily.FieldTotalBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UserCount(); ok {
		_spec.SetField(balancesnapshotdaily.FieldUserCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserCount(); ok {
		_spec.AddField(balancesnapshotdaily.FieldUserCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ComputedAt(); ok {
		_spec.SetField(balancesnapshotdaily.FieldComputedAt, field.TypeTime, value)
	}
	_node = &BalanceSnapshotDaily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancesnapshotdaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
