// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancesnapshotdaily"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceSnapshotDailyDelete is the builder for deleting a BalanceSnapshotDaily entity.
type BalanceSnapshotDailyDelete struct {
	config
	hooks    []Hook
	mutation *BalanceSnapshotDailyMutation
}

// Where appends a list predicates to the BalanceSnapshotDailyDelete builder.
func (_d *BalanceSnapshotDailyDelete) Where(ps ...predicate.BalanceSnapshotDaily) *BalanceSnapshotDailyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BalanceSnapshotDailyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceSnapshotDailyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BalanceSnapshotDailyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(balancesnapshotdaily.Table, sqlgraph.NewFieldSpec(balancesnapshotdaily.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BalanceSnapshotDailyDeleteOne is the builder for deleting a single BalanceSnapshotDaily entity.
type BalanceSnapshotDailyDeleteOne struct {
	_d *BalanceSnapshotDailyDelete
}

// Where appends a list predicates to the BalanceSnapshotDailyDelete builder.
func (_d *BalanceSnapshotDailyDeleteOne) Where(ps ...predicate.BalanceSnapshotDaily) *BalanceSnapshotDailyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BalanceSnapshotDailyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{balancesnapshotdaily.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BalanceSnapshotDailyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
