// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTradeNo sets the "trade_no" field.
func (_c *PaymentOrderCreate) SetTradeNo(v string) *PaymentOrderCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v int64) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentOrderCreate) SetAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPaymentAmount sets the "payment_amount" field.
func (_c *PaymentOrderCreate) SetPaymentAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetPaymentAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *PaymentOrderCreate) SetExpiredAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_c *PaymentOrderCreate) SetAlipayTradeNo(v string) *PaymentOrderCreate {
	_c.mutation.SetAlipayTradeNo(v)
	return _c
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAlipayTradeNo(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetAlipayTradeNo(*v)
	}
	return _c
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (_c *PaymentOrderCreate) SetAlipayTransLogID(v string) *PaymentOrderCreate {
	_c.mutation.SetAlipayTransLogID(v)
	return _c
}

// SetNillableAlipayTransLogID sets the "alipay_trans_log_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAlipayTransLogID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetAlipayTransLogID(*v)
	}
	return _c
}

// SetPayerAccount sets the "payer_account" field.
func (_c *PaymentOrderCreate) SetPayerAccount(v string) *PaymentOrderCreate {
	_c.mutation.SetPayerAccount(v)
	return _c
}

// SetNillablePayerAccount sets the "payer_account" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePayerAccount(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetPayerAccount(*v)
	}
	return _c
}

// SetCreditAmount sets the "credit_amount" field.
func (_c *PaymentOrderCreate) SetCreditAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetCreditAmount(v)
	return _c
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreditAmount(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreditAmount(*v)
	}
	return _c
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (_c *PaymentOrderCreate) SetRateCoefficient(v float64) *PaymentOrderCreate {
	_c.mutation.SetRateCoefficient(v)
	return _c
}

// SetNillableRateCoefficient sets the "rate_coefficient" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableRateCoefficient(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetRateCoefficient(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PaymentOrderCreate) SetNotes(v string) *PaymentOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableNotes(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.RateCoefficient(); !ok {
		v := paymentorder.DefaultRateCoefficient
		_c.mutation.SetRateCoefficient(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.TradeNo(); !ok {
		return &ValidationError{Name: "trade_no", err: errors.New(`ent: missing required field "PaymentOrder.trade_no"`)}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := paymentorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := paymentorder.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentAmount(); !ok {
		return &ValidationError{Name: "payment_amount", err: errors.New(`ent: missing required field "PaymentOrder.payment_amount"`)}
	}
	if v, ok := _c.mutation.PaymentAmount(); ok {
		if err := paymentorder.PaymentAmountValidator(v); err != nil {
			return &ValidationError{Name: "payment_amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payment_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "PaymentOrder.expired_at"`)}
	}
	if v, ok := _c.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AlipayTransLogID(); ok {
		if err := paymentorder.AlipayTransLogIDValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trans_log_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trans_log_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PayerAccount(); ok {
		if err := paymentorder.PayerAccountValidator(v); err != nil {
			return &ValidationError{Name: "payer_account", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payer_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateCoefficient(); !ok {
		return &ValidationError{Name: "rate_coefficient", err: errors.New(`ent: missing required field "PaymentOrder.rate_coefficient"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.PaymentAmount(); ok {
		_spec.SetField(paymentorder.FieldPaymentAmount, field.TypeFloat64, value)
		_node.PaymentAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := _c.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
		_node.AlipayTradeNo = &value
	}
	if value, ok := _c.mutation.AlipayTransLogID(); ok {
		_spec.SetField(paymentorder.FieldAlipayTransLogID, field.TypeString, value)
		_node.AlipayTransLogID = &value
	}
	if value, ok := _c.mutation.PayerAccount(); ok {
		_spec.SetField(paymentorder.FieldPayerAccount, field.TypeString, value)
		_node.PayerAccount = &value
	}
	if value, ok := _c.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
		_node.CreditAmount = &value
	}
	if value, ok := _c.mutation.RateCoefficient(); ok {
		_spec.SetField(paymentorder.FieldRateCoefficient, field.TypeFloat64, value)
		_node.RateCoefficient = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(paymentorder.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetTradeNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetTradeNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	_c.conflict = opts
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetTradeNo sets the "trade_no" field.
func (u *PaymentOrderUpsert) SetTradeNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldTradeNo, v)
	return u
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateTradeNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldTradeNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsert) SetAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsert) AddAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmount, v)
	return u
}

// SetPaymentAmount sets the "payment_amount" field.
func (u *PaymentOrderUpsert) SetPaymentAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaymentAmount, v)
	return u
}

// UpdatePaymentAmount sets the "payment_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaymentAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaymentAmount)
	return u
}

// AddPaymentAmount adds v to the "payment_amount" field.
func (u *PaymentOrderUpsert) AddPaymentAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldPaymentAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsert) SetPaidAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaidAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsert) ClearPaidAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPaidAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsert) SetExpiredAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateExpiredAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldExpiredAt)
	return u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsert) SetAlipayTradeNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAlipayTradeNo, v)
	return u
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAlipayTradeNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAlipayTradeNo)
	return u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsert) ClearAlipayTradeNo() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldAlipayTradeNo)
	return u
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsert) SetAlipayTransLogID(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAlipayTransLogID, v)
	return u
}

// UpdateAlipayTransLogID sets the "alipay_trans_log_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAlipayTransLogID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAlipayTransLogID)
	return u
}

// ClearAlipayTransLogID clears the value of the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsert) ClearAlipayTransLogID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldAlipayTransLogID)
	return u
}

// SetPayerAccount sets the "payer_account" field.
func (u *PaymentOrderUpsert) SetPayerAccount(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPayerAccount, v)
	return u
}

// UpdatePayerAccount sets the "payer_account" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePayerAccount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPayerAccount)
	return u
}

// ClearPayerAccount clears the value of the "payer_account" field.
func (u *PaymentOrderUpsert) ClearPayerAccount() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPayerAccount)
	return u
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsert) SetCreditAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCreditAmount, v)
	return u
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCreditAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCreditAmount)
	return u
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsert) AddCreditAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldCreditAmount, v)
	return u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsert) ClearCreditAmount() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldCreditAmount)
	return u
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (u *PaymentOrderUpsert) SetRateCoefficient(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldRateCoefficient, v)
	return u
}

// UpdateRateCoefficient sets the "rate_coefficient" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateRateCoefficient() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldRateCoefficient)
	return u
}

// AddRateCoefficient adds v to the "rate_coefficient" field.
func (u *PaymentOrderUpsert) AddRateCoefficient(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldRateCoefficient, v)
	return u
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsert) SetNotes(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateNotes() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsert) ClearNotes() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetTradeNo sets the "trade_no" field.
func (u *PaymentOrderUpsertOne) SetTradeNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateTradeNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertOne) SetAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertOne) AddAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaymentAmount sets the "payment_amount" field.
func (u *PaymentOrderUpsertOne) SetPaymentAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaymentAmount(v)
	})
}

// AddPaymentAmount adds v to the "payment_amount" field.
func (u *PaymentOrderUpsertOne) AddPaymentAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddPaymentAmount(v)
	})
}

// UpdatePaymentAmount sets the "payment_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaymentAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaymentAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertOne) SetPaidAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertOne) ClearPaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertOne) SetExpiredAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateExpiredAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsertOne) SetAlipayTradeNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAlipayTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsertOne) ClearAlipayTradeNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsertOne) SetAlipayTransLogID(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTransLogID(v)
	})
}

// UpdateAlipayTransLogID sets the "alipay_trans_log_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAlipayTransLogID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTransLogID()
	})
}

// ClearAlipayTransLogID clears the value of the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsertOne) ClearAlipayTransLogID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTransLogID()
	})
}

// SetPayerAccount sets the "payer_account" field.
func (u *PaymentOrderUpsertOne) SetPayerAccount(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayerAccount(v)
	})
}

// UpdatePayerAccount sets the "payer_account" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePayerAccount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayerAccount()
	})
}

// ClearPayerAccount clears the value of the "payer_account" field.
func (u *PaymentOrderUpsertOne) ClearPayerAccount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPayerAccount()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsertOne) SetCreditAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsertOne) AddCreditAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCreditAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsertOne) ClearCreditAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCreditAmount()
	})
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (u *PaymentOrderUpsertOne) SetRateCoefficient(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRateCoefficient(v)
	})
}

// AddRateCoefficient adds v to the "rate_coefficient" field.
func (u *PaymentOrderUpsertOne) AddRateCoefficient(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddRateCoefficient(v)
	})
}

// UpdateRateCoefficient sets the "rate_coefficient" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateRateCoefficient() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRateCoefficient()
	})
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsertOne) SetNotes(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateNotes() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsertOne) ClearNotes() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetTradeNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetTradeNo sets the "trade_no" field.
func (u *PaymentOrderUpsertBulk) SetTradeNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateTradeNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertBulk) SetAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertBulk) AddAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaymentAmount sets the "payment_amount" field.
func (u *PaymentOrderUpsertBulk) SetPaymentAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaymentAmount(v)
	})
}

// AddPaymentAmount adds v to the "payment_amount" field.
func (u *PaymentOrderUpsertBulk) AddPaymentAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddPaymentAmount(v)
	})
}

// UpdatePaymentAmount sets the "payment_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaymentAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaymentAmount()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertBulk) ClearPaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertBulk) SetExpiredAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateExpiredAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (u *PaymentOrderUpsertBulk) SetAlipayTradeNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTradeNo(v)
	})
}

// UpdateAlipayTradeNo sets the "alipay_trade_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAlipayTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTradeNo()
	})
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (u *PaymentOrderUpsertBulk) ClearAlipayTradeNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTradeNo()
	})
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsertBulk) SetAlipayTransLogID(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAlipayTransLogID(v)
	})
}

// UpdateAlipayTransLogID sets the "alipay_trans_log_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAlipayTransLogID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAlipayTransLogID()
	})
}

// ClearAlipayTransLogID clears the value of the "alipay_trans_log_id" field.
func (u *PaymentOrderUpsertBulk) ClearAlipayTransLogID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAlipayTransLogID()
	})
}

// SetPayerAccount sets the "payer_account" field.
func (u *PaymentOrderUpsertBulk) SetPayerAccount(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPayerAccount(v)
	})
}

// UpdatePayerAccount sets the "payer_account" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePayerAccount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePayerAccount()
	})
}

// ClearPayerAccount clears the value of the "payer_account" field.
func (u *PaymentOrderUpsertBulk) ClearPayerAccount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPayerAccount()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) SetCreditAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) AddCreditAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCreditAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) ClearCreditAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCreditAmount()
	})
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (u *PaymentOrderUpsertBulk) SetRateCoefficient(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRateCoefficient(v)
	})
}

// AddRateCoefficient adds v to the "rate_coefficient" field.
func (u *PaymentOrderUpsertBulk) AddRateCoefficient(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddRateCoefficient(v)
	})
}

// UpdateRateCoefficient sets the "rate_coefficient" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateRateCoefficient() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRateCoefficient()
	})
}

// SetNotes sets the "notes" field.
func (u *PaymentOrderUpsertBulk) SetNotes(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateNotes() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PaymentOrderUpsertBulk) ClearNotes() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
