// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdate) SetTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdate) SetAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdate) AddAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPaymentAmount sets the "payment_amount" field.
func (_u *PaymentOrderUpdate) SetPaymentAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetPaymentAmount()
	_u.mutation.SetPaymentAmount(v)
	return _u
}

// SetNillablePaymentAmount sets the "payment_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaymentAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaymentAmount(*v)
	}
	return _u
}

// AddPaymentAmount adds value to the "payment_amount" field.
func (_u *PaymentOrderUpdate) AddPaymentAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddPaymentAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *PaymentOrderUpdate) SetExpiredAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableExpiredAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *PaymentOrderUpdate) SetAlipayTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAlipayTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *PaymentOrderUpdate) ClearAlipayTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (_u *PaymentOrderUpdate) SetAlipayTransLogID(v string) *PaymentOrderUpdate {
	_u.mutation.SetAlipayTransLogID(v)
	return _u
}

// SetNillableAlipayTransLogID sets the "alipay_trans_log_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAlipayTransLogID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAlipayTransLogID(*v)
	}
	return _u
}

// ClearAlipayTransLogID clears the value of the "alipay_trans_log_id" field.
func (_u *PaymentOrderUpdate) ClearAlipayTransLogID() *PaymentOrderUpdate {
	_u.mutation.ClearAlipayTransLogID()
	return _u
}

// SetPayerAccount sets the "payer_account" field.
func (_u *PaymentOrderUpdate) SetPayerAccount(v string) *PaymentOrderUpdate {
	_u.mutation.SetPayerAccount(v)
	return _u
}

// SetNillablePayerAccount sets the "payer_account" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePayerAccount(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPayerAccount(*v)
	}
	return _u
}

// ClearPayerAccount clears the value of the "payer_account" field.
func (_u *PaymentOrderUpdate) ClearPayerAccount() *PaymentOrderUpdate {
	_u.mutation.ClearPayerAccount()
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaymentOrderUpdate) SetCreditAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCreditAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaymentOrderUpdate) AddCreditAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (_u *PaymentOrderUpdate) ClearCreditAmount() *PaymentOrderUpdate {
	_u.mutation.ClearCreditAmount()
	return _u
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (_u *PaymentOrderUpdate) SetRateCoefficient(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetRateCoefficient()
	_u.mutation.SetRateCoefficient(v)
	return _u
}

// SetNillableRateCoefficient sets the "rate_coefficient" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRateCoefficient(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRateCoefficient(*v)
	}
	return _u
}

// AddRateCoefficient adds value to the "rate_coefficient" field.
func (_u *PaymentOrderUpdate) AddRateCoefficient(v float64) *PaymentOrderUpdate {
	_u.mutation.AddRateCoefficient(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PaymentOrderUpdate) SetNotes(v string) *PaymentOrderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableNotes(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PaymentOrderUpdate) ClearNotes() *PaymentOrderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymentorder.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAmount(); ok {
		if err := paymentorder.PaymentAmountValidator(v); err != nil {
			return &ValidationError{Name: "payment_amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payment_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTransLogID(); ok {
		if err := paymentorder.AlipayTransLogIDValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trans_log_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trans_log_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayerAccount(); ok {
		if err := paymentorder.PayerAccountValidator(v); err != nil {
			return &ValidationError{Name: "payer_account", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payer_account": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentAmount(); ok {
		_spec.SetField(paymentorder.FieldPaymentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPaymentAmount(); ok {
		_spec.AddField(paymentorder.FieldPaymentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AlipayTransLogID(); ok {
		_spec.SetField(paymentorder.FieldAlipayTransLogID, field.TypeString, value)
	}
	if _u.mutation.AlipayTransLogIDCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTransLogID, field.TypeString)
	}
	if value, ok := _u.mutation.PayerAccount(); ok {
		_spec.SetField(paymentorder.FieldPayerAccount, field.TypeString, value)
	}
	if _u.mutation.PayerAccountCleared() {
		_spec.ClearField(paymentorder.FieldPayerAccount, field.TypeString)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CreditAmountCleared() {
		_spec.ClearField(paymentorder.FieldCreditAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateCoefficient(); ok {
		_spec.SetField(paymentorder.FieldRateCoefficient, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateCoefficient(); ok {
		_spec.AddField(paymentorder.FieldRateCoefficient, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(paymentorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(paymentorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdateOne) SetTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdateOne) SetAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdateOne) AddAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetPaymentAmount sets the "payment_amount" field.
func (_u *PaymentOrderUpdateOne) SetPaymentAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetPaymentAmount()
	_u.mutation.SetPaymentAmount(v)
	return _u
}

// SetNillablePaymentAmount sets the "payment_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaymentAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaymentAmount(*v)
	}
	return _u
}

// AddPaymentAmount adds value to the "payment_amount" field.
func (_u *PaymentOrderUpdateOne) AddPaymentAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddPaymentAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *PaymentOrderUpdateOne) SetExpiredAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableExpiredAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetAlipayTradeNo sets the "alipay_trade_no" field.
func (_u *PaymentOrderUpdateOne) SetAlipayTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetAlipayTradeNo(v)
	return _u
}

// SetNillableAlipayTradeNo sets the "alipay_trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAlipayTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAlipayTradeNo(*v)
	}
	return _u
}

// ClearAlipayTradeNo clears the value of the "alipay_trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearAlipayTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearAlipayTradeNo()
	return _u
}

// SetAlipayTransLogID sets the "alipay_trans_log_id" field.
func (_u *PaymentOrderUpdateOne) SetAlipayTransLogID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetAlipayTransLogID(v)
	return _u
}

// SetNillableAlipayTransLogID sets the "alipay_trans_log_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAlipayTransLogID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAlipayTransLogID(*v)
	}
	return _u
}

// ClearAlipayTransLogID clears the value of the "alipay_trans_log_id" field.
func (_u *PaymentOrderUpdateOne) ClearAlipayTransLogID() *PaymentOrderUpdateOne {
	_u.mutation.ClearAlipayTransLogID()
	return _u
}

// SetPayerAccount sets the "payer_account" field.
func (_u *PaymentOrderUpdateOne) SetPayerAccount(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetPayerAccount(v)
	return _u
}

// SetNillablePayerAccount sets the "payer_account" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePayerAccount(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPayerAccount(*v)
	}
	return _u
}

// ClearPayerAccount clears the value of the "payer_account" field.
func (_u *PaymentOrderUpdateOne) ClearPayerAccount() *PaymentOrderUpdateOne {
	_u.mutation.ClearPayerAccount()
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) SetCreditAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCreditAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) AddCreditAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) ClearCreditAmount() *PaymentOrderUpdateOne {
	_u.mutation.ClearCreditAmount()
	return _u
}

// SetRateCoefficient sets the "rate_coefficient" field.
func (_u *PaymentOrderUpdateOne) SetRateCoefficient(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetRateCoefficient()
	_u.mutation.SetRateCoefficient(v)
	return _u
}

// SetNillableRateCoefficient sets the "rate_coefficient" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRateCoefficient(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRateCoefficient(*v)
	}
	return _u
}

// AddRateCoefficient adds value to the "rate_coefficient" field.
func (_u *PaymentOrderUpdateOne) AddRateCoefficient(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddRateCoefficient(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PaymentOrderUpdateOne) SetNotes(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableNotes(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PaymentOrderUpdateOne) ClearNotes() *PaymentOrderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymentorder.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentAmount(); ok {
		if err := paymentorder.PaymentAmountValidator(v); err != nil {
			return &ValidationError{Name: "payment_amount", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payment_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTradeNo(); ok {
		if err := paymentorder.AlipayTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AlipayTransLogID(); ok {
		if err := paymentorder.AlipayTransLogIDValidator(v); err != nil {
			return &ValidationError{Name: "alipay_trans_log_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.alipay_trans_log_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayerAccount(); ok {
		if err := paymentorder.PayerAccountValidator(v); err != nil {
			return &ValidationError{Name: "payer_account", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payer_account": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentAmount(); ok {
		_spec.SetField(paymentorder.FieldPaymentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPaymentAmount(); ok {
		_spec.AddField(paymentorder.FieldPaymentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AlipayTradeNo(); ok {
		_spec.SetField(paymentorder.FieldAlipayTradeNo, field.TypeString, value)
	}
	if _u.mutation.AlipayTradeNoCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AlipayTransLogID(); ok {
		_spec.SetField(paymentorder.FieldAlipayTransLogID, field.TypeString, value)
	}
	if _u.mutation.AlipayTransLogIDCleared() {
		_spec.ClearField(paymentorder.FieldAlipayTransLogID, field.TypeString)
	}
	if value, ok := _u.mutation.PayerAccount(); ok {
		_spec.SetField(paymentorder.FieldPayerAccount, field.TypeString, value)
	}
	if _u.mutation.PayerAccountCleared() {
		_spec.ClearField(paymentorder.FieldPayerAccount, field.TypeString)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CreditAmountCleared() {
		_spec.ClearField(paymentorder.FieldCreditAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RateCoefficient(); ok {
		_spec.SetField(paymentorder.FieldRateCoefficient, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateCoefficient(); ok {
		_spec.AddField(paymentorder.FieldRateCoefficient, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(paymentorder.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(paymentorder.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
