// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemrule"
)

// RedeemRuleCreate is the builder for creating a RedeemRule entity.
type RedeemRuleCreate struct {
	config
	mutation *RedeemRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (_c *RedeemRuleCreate) SetType(v string) *RedeemRuleCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableType(v *string) *RedeemRuleCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetTriggerValue sets the "trigger_value" field.
func (_c *RedeemRuleCreate) SetTriggerValue(v float64) *RedeemRuleCreate {
	_c.mutation.SetTriggerValue(v)
	return _c
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (_c *RedeemRuleCreate) SetMaxTimesPerUser(v int) *RedeemRuleCreate {
	_c.mutation.SetMaxTimesPerUser(v)
	return _c
}

// SetNillableMaxTimesPerUser sets the "max_times_per_user" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableMaxTimesPerUser(v *int) *RedeemRuleCreate {
	if v != nil {
		_c.SetMaxTimesPerUser(*v)
	}
	return _c
}

// SetFallbackValue sets the "fallback_value" field.
func (_c *RedeemRuleCreate) SetFallbackValue(v float64) *RedeemRuleCreate {
	_c.mutation.SetFallbackValue(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *RedeemRuleCreate) SetIsActive(v bool) *RedeemRuleCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableIsActive(v *bool) *RedeemRuleCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RedeemRuleCreate) SetDescription(v string) *RedeemRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableDescription(v *string) *RedeemRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RedeemRuleCreate) SetCreatedAt(v time.Time) *RedeemRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableCreatedAt(v *time.Time) *RedeemRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RedeemRuleCreate) SetUpdatedAt(v time.Time) *RedeemRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RedeemRuleCreate) SetNillableUpdatedAt(v *time.Time) *RedeemRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemRuleMutation object of the builder.
func (_c *RedeemRuleCreate) Mutation() *RedeemRuleMutation {
	return _c.mutation
}

// Save creates the RedeemRule in the database.
func (_c *RedeemRuleCreate) Save(ctx context.Context) (*RedeemRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemRuleCreate) SaveX(ctx context.Context) *RedeemRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemRuleCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := redeemrule.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.MaxTimesPerUser(); !ok {
		v := redeemrule.DefaultMaxTimesPerUser
		_c.mutation.SetMaxTimesPerUser(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := redeemrule.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := redeemrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := redeemrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemRuleCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "RedeemRule.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := redeemrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RedeemRule.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerValue(); !ok {
		return &ValidationError{Name: "trigger_value", err: errors.New(`ent: missing required field "RedeemRule.trigger_value"`)}
	}
	if _, ok := _c.mutation.MaxTimesPerUser(); !ok {
		return &ValidationError{Name: "max_times_per_user", err: errors.New(`ent: missing required field "RedeemRule.max_times_per_user"`)}
	}
	if _, ok := _c.mutation.FallbackValue(); !ok {
		return &ValidationError{Name: "fallback_value", err: errors.New(`ent: missing required field "RedeemRule.fallback_value"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "RedeemRule.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RedeemRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RedeemRule.updated_at"`)}
	}
	return nil
}

func (_c *RedeemRuleCreate) sqlSave(ctx context.Context) (*RedeemRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemRuleCreate) createSpec() (*RedeemRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemrule.Table, sqlgraph.NewFieldSpec(redeemrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(redeemrule.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.TriggerValue(); ok {
		_spec.SetField(redeemrule.FieldTriggerValue, field.TypeFloat64, value)
		_node.TriggerValue = value
	}
	if value, ok := _c.mutation.MaxTimesPerUser(); ok {
		_spec.SetField(redeemrule.FieldMaxTimesPerUser, field.TypeInt, value)
		_node.MaxTimesPerUser = value
	}
	if value, ok := _c.mutation.FallbackValue(); ok {
		_spec.SetField(redeemrule.FieldFallbackValue, field.TypeFloat64, value)
		_node.FallbackValue = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(redeemrule.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(redeemrule.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(redeemrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(redeemrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemRule.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemRuleUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemRuleCreate) OnConflict(opts ...sql.ConflictOption) *RedeemRuleUpsertOne {
	_c.conflict = opts
	return &RedeemRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemRuleCreate) OnConflictColumns(columns ...string) *RedeemRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemRuleUpsertOne{
		create: _c,
	}
}

type (
	// RedeemRuleUpsertOne is the builder for "upsert"-ing
	//  one RedeemRule node.
	RedeemRuleUpsertOne struct {
		create *RedeemRuleCreate
	}

	// RedeemRuleUpsert is the "OnConflict" setter.
	RedeemRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *RedeemRuleUpsert) SetType(v string) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateType() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldType)
	return u
}

// SetTriggerValue sets the "trigger_value" field.
func (u *RedeemRuleUpsert) SetTriggerValue(v float64) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldTriggerValue, v)
	return u
}

// UpdateTriggerValue sets the "trigger_value" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateTriggerValue() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldTriggerValue)
	return u
}

// AddTriggerValue adds v to the "trigger_value" field.
func (u *RedeemRuleUpsert) AddTriggerValue(v float64) *RedeemRuleUpsert {
	u.Add(redeemrule.FieldTriggerValue, v)
	return u
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (u *RedeemRuleUpsert) SetMaxTimesPerUser(v int) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldMaxTimesPerUser, v)
	return u
}

// UpdateMaxTimesPerUser sets the "max_times_per_user" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateMaxTimesPerUser() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldMaxTimesPerUser)
	return u
}

// AddMaxTimesPerUser adds v to the "max_times_per_user" field.
func (u *RedeemRuleUpsert) AddMaxTimesPerUser(v int) *RedeemRuleUpsert {
	u.Add(redeemrule.FieldMaxTimesPerUser, v)
	return u
}

// SetFallbackValue sets the "fallback_value" field.
func (u *RedeemRuleUpsert) SetFallbackValue(v float64) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldFallbackValue, v)
	return u
}

// UpdateFallbackValue sets the "fallback_value" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateFallbackValue() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldFallbackValue)
	return u
}

// AddFallbackValue adds v to the "fallback_value" field.
func (u *RedeemRuleUpsert) AddFallbackValue(v float64) *RedeemRuleUpsert {
	u.Add(redeemrule.FieldFallbackValue, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *RedeemRuleUpsert) SetIsActive(v bool) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateIsActive() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldIsActive)
	return u
}

// SetDescription sets the "description" field.
func (u *RedeemRuleUpsert) SetDescription(v string) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateDescription() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *RedeemRuleUpsert) ClearDescription() *RedeemRuleUpsert {
	u.SetNull(redeemrule.FieldDescription)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemRuleUpsert) SetUpdatedAt(v time.Time) *RedeemRuleUpsert {
	u.Set(redeemrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemRuleUpsert) UpdateUpdatedAt() *RedeemRuleUpsert {
	u.SetExcluded(redeemrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemRuleUpsertOne) UpdateNewValues() *RedeemRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(redeemrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemRuleUpsertOne) Ignore() *RedeemRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemRuleUpsertOne) DoNothing() *RedeemRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemRuleCreate.OnConflict
// documentation for more info.
func (u *RedeemRuleUpsertOne) Update(set func(*RedeemRuleUpsert)) *RedeemRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *RedeemRuleUpsertOne) SetType(v string) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateType() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateType()
	})
}

// SetTriggerValue sets the "trigger_value" field.
func (u *RedeemRuleUpsertOne) SetTriggerValue(v float64) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetTriggerValue(v)
	})
}

// AddTriggerValue adds v to the "trigger_value" field.
func (u *RedeemRuleUpsertOne) AddTriggerValue(v float64) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddTriggerValue(v)
	})
}

// UpdateTriggerValue sets the "trigger_value" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateTriggerValue() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateTriggerValue()
	})
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (u *RedeemRuleUpsertOne) SetMaxTimesPerUser(v int) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetMaxTimesPerUser(v)
	})
}

// AddMaxTimesPerUser adds v to the "max_times_per_user" field.
func (u *RedeemRuleUpsertOne) AddMaxTimesPerUser(v int) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddMaxTimesPerUser(v)
	})
}

// UpdateMaxTimesPerUser sets the "max_times_per_user" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateMaxTimesPerUser() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateMaxTimesPerUser()
	})
}

// SetFallbackValue sets the "fallback_value" field.
func (u *RedeemRuleUpsertOne) SetFallbackValue(v float64) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetFallbackValue(v)
	})
}

// AddFallbackValue adds v to the "fallback_value" field.
func (u *RedeemRuleUpsertOne) AddFallbackValue(v float64) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddFallbackValue(v)
	})
}

// UpdateFallbackValue sets the "fallback_value" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateFallbackValue() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateFallbackValue()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RedeemRuleUpsertOne) SetIsActive(v bool) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateIsActive() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetDescription sets the "description" field.
func (u *RedeemRuleUpsertOne) SetDescription(v string) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateDescription() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RedeemRuleUpsertOne) ClearDescription() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.ClearDescription()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemRuleUpsertOne) SetUpdatedAt(v time.Time) *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemRuleUpsertOne) UpdateUpdatedAt() *RedeemRuleUpsertOne {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RedeemRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemRuleCreateBulk is the builder for creating many RedeemRule entities in bulk.
type RedeemRuleCreateBulk struct {
	config
	err      error
	builders []*RedeemRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemRule entities in the database.
func (_c *RedeemRuleCreateBulk) Save(ctx context.Context) ([]*RedeemRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemRuleCreateBulk) SaveX(ctx context.Context) []*RedeemRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemRuleUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemRuleUpsertBulk {
	_c.conflict = opts
	return &RedeemRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemRuleCreateBulk) OnConflictColumns(columns ...string) *RedeemRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemRuleUpsertBulk{
		create: _c,
	}
}

// RedeemRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemRule nodes.
type RedeemRuleUpsertBulk struct {
	create *RedeemRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemRuleUpsertBulk) UpdateNewValues() *RedeemRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(redeemrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemRuleUpsertBulk) Ignore() *RedeemRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemRuleUpsertBulk) DoNothing() *RedeemRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemRuleCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemRuleUpsertBulk) Update(set func(*RedeemRuleUpsert)) *RedeemRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *RedeemRuleUpsertBulk) SetType(v string) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateType() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateType()
	})
}

// SetTriggerValue sets the "trigger_value" field.
func (u *RedeemRuleUpsertBulk) SetTriggerValue(v float64) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetTriggerValue(v)
	})
}

// AddTriggerValue adds v to the "trigger_value" field.
func (u *RedeemRuleUpsertBulk) AddTriggerValue(v float64) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddTriggerValue(v)
	})
}

// UpdateTriggerValue sets the "trigger_value" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateTriggerValue() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateTriggerValue()
	})
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (u *RedeemRuleUpsertBulk) SetMaxTimesPerUser(v int) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetMaxTimesPerUser(v)
	})
}

// AddMaxTimesPerUser adds v to the "max_times_per_user" field.
func (u *RedeemRuleUpsertBulk) AddMaxTimesPerUser(v int) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddMaxTimesPerUser(v)
	})
}

// UpdateMaxTimesPerUser sets the "max_times_per_user" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateMaxTimesPerUser() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateMaxTimesPerUser()
	})
}

// SetFallbackValue sets the "fallback_value" field.
func (u *RedeemRuleUpsertBulk) SetFallbackValue(v float64) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetFallbackValue(v)
	})
}

// AddFallbackValue adds v to the "fallback_value" field.
func (u *RedeemRuleUpsertBulk) AddFallbackValue(v float64) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.AddFallbackValue(v)
	})
}

// UpdateFallbackValue sets the "fallback_value" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateFallbackValue() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateFallbackValue()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RedeemRuleUpsertBulk) SetIsActive(v bool) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateIsActive() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateIsActive()
	})
}

// SetDescription sets the "description" field.
func (u *RedeemRuleUpsertBulk) SetDescription(v string) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateDescription() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RedeemRuleUpsertBulk) ClearDescription() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.ClearDescription()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RedeemRuleUpsertBulk) SetUpdatedAt(v time.Time) *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RedeemRuleUpsertBulk) UpdateUpdatedAt() *RedeemRuleUpsertBulk {
	return u.Update(func(s *RedeemRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RedeemRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
