// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemrule"
)

// RedeemRuleUpdate is the builder for updating RedeemRule entities.
type RedeemRuleUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemRuleMutation
}

// Where appends a list predicates to the RedeemRuleUpdate builder.
func (_u *RedeemRuleUpdate) Where(ps ...predicate.RedeemRule) *RedeemRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *RedeemRuleUpdate) SetType(v string) *RedeemRuleUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableType(v *string) *RedeemRuleUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTriggerValue sets the "trigger_value" field.
func (_u *RedeemRuleUpdate) SetTriggerValue(v float64) *RedeemRuleUpdate {
	_u.mutation.ResetTriggerValue()
	_u.mutation.SetTriggerValue(v)
	return _u
}

// SetNillableTriggerValue sets the "trigger_value" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableTriggerValue(v *float64) *RedeemRuleUpdate {
	if v != nil {
		_u.SetTriggerValue(*v)
	}
	return _u
}

// AddTriggerValue adds value to the "trigger_value" field.
func (_u *RedeemRuleUpdate) AddTriggerValue(v float64) *RedeemRuleUpdate {
	_u.mutation.AddTriggerValue(v)
	return _u
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (_u *RedeemRuleUpdate) SetMaxTimesPerUser(v int) *RedeemRuleUpdate {
	_u.mutation.ResetMaxTimesPerUser()
	_u.mutation.SetMaxTimesPerUser(v)
	return _u
}

// SetNillableMaxTimesPerUser sets the "max_times_per_user" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableMaxTimesPerUser(v *int) *RedeemRuleUpdate {
	if v != nil {
		_u.SetMaxTimesPerUser(*v)
	}
	return _u
}

// AddMaxTimesPerUser adds value to the "max_times_per_user" field.
func (_u *RedeemRuleUpdate) AddMaxTimesPerUser(v int) *RedeemRuleUpdate {
	_u.mutation.AddMaxTimesPerUser(v)
	return _u
}

// SetFallbackValue sets the "fallback_value" field.
func (_u *RedeemRuleUpdate) SetFallbackValue(v float64) *RedeemRuleUpdate {
	_u.mutation.ResetFallbackValue()
	_u.mutation.SetFallbackValue(v)
	return _u
}

// SetNillableFallbackValue sets the "fallback_value" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableFallbackValue(v *float64) *RedeemRuleUpdate {
	if v != nil {
		_u.SetFallbackValue(*v)
	}
	return _u
}

// AddFallbackValue adds value to the "fallback_value" field.
func (_u *RedeemRuleUpdate) AddFallbackValue(v float64) *RedeemRuleUpdate {
	_u.mutation.AddFallbackValue(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *RedeemRuleUpdate) SetIsActive(v bool) *RedeemRuleUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableIsActive(v *bool) *RedeemRuleUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RedeemRuleUpdate) SetDescription(v string) *RedeemRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RedeemRuleUpdate) SetNillableDescription(v *string) *RedeemRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RedeemRuleUpdate) ClearDescription() *RedeemRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RedeemRuleUpdate) SetUpdatedAt(v time.Time) *RedeemRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RedeemRuleMutation object of the builder.
func (_u *RedeemRuleUpdate) Mutation() *RedeemRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RedeemRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := redeemrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemRuleUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := redeemrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RedeemRule.type": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemrule.Table, redeemrule.Columns, sqlgraph.NewFieldSpec(redeemrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(redeemrule.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerValue(); ok {
		_spec.SetField(redeemrule.FieldTriggerValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTriggerValue(); ok {
		_spec.AddField(redeemrule.FieldTriggerValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTimesPerUser(); ok {
		_spec.SetField(redeemrule.FieldMaxTimesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTimesPerUser(); ok {
		_spec.AddField(redeemrule.FieldMaxTimesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FallbackValue(); ok {
		_spec.SetField(redeemrule.FieldFallbackValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFallbackValue(); ok {
		_spec.AddField(redeemrule.FieldFallbackValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(redeemrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(redeemrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(redeemrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(redeemrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemRuleUpdateOne is the builder for updating a single RedeemRule entity.
type RedeemRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemRuleMutation
}

// SetType sets the "type" field.
func (_u *RedeemRuleUpdateOne) SetType(v string) *RedeemRuleUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableType(v *string) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTriggerValue sets the "trigger_value" field.
func (_u *RedeemRuleUpdateOne) SetTriggerValue(v float64) *RedeemRuleUpdateOne {
	_u.mutation.ResetTriggerValue()
	_u.mutation.SetTriggerValue(v)
	return _u
}

// SetNillableTriggerValue sets the "trigger_value" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableTriggerValue(v *float64) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetTriggerValue(*v)
	}
	return _u
}

// AddTriggerValue adds value to the "trigger_value" field.
func (_u *RedeemRuleUpdateOne) AddTriggerValue(v float64) *RedeemRuleUpdateOne {
	_u.mutation.AddTriggerValue(v)
	return _u
}

// SetMaxTimesPerUser sets the "max_times_per_user" field.
func (_u *RedeemRuleUpdateOne) SetMaxTimesPerUser(v int) *RedeemRuleUpdateOne {
	_u.mutation.ResetMaxTimesPerUser()
	_u.mutation.SetMaxTimesPerUser(v)
	return _u
}

// SetNillableMaxTimesPerUser sets the "max_times_per_user" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableMaxTimesPerUser(v *int) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetMaxTimesPerUser(*v)
	}
	return _u
}

// AddMaxTimesPerUser adds value to the "max_times_per_user" field.
func (_u *RedeemRuleUpdateOne) AddMaxTimesPerUser(v int) *RedeemRuleUpdateOne {
	_u.mutation.AddMaxTimesPerUser(v)
	return _u
}

// SetFallbackValue sets the "fallback_value" field.
func (_u *RedeemRuleUpdateOne) SetFallbackValue(v float64) *RedeemRuleUpdateOne {
	_u.mutation.ResetFallbackValue()
	_u.mutation.SetFallbackValue(v)
	return _u
}

// SetNillableFallbackValue sets the "fallback_value" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableFallbackValue(v *float64) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetFallbackValue(*v)
	}
	return _u
}

// AddFallbackValue adds value to the "fallback_value" field.
func (_u *RedeemRuleUpdateOne) AddFallbackValue(v float64) *RedeemRuleUpdateOne {
	_u.mutation.AddFallbackValue(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *RedeemRuleUpdateOne) SetIsActive(v bool) *RedeemRuleUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableIsActive(v *bool) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RedeemRuleUpdateOne) SetDescription(v string) *RedeemRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RedeemRuleUpdateOne) SetNillableDescription(v *string) *RedeemRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RedeemRuleUpdateOne) ClearDescription() *RedeemRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RedeemRuleUpdateOne) SetUpdatedAt(v time.Time) *RedeemRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RedeemRuleMutation object of the builder.
func (_u *RedeemRuleUpdateOne) Mutation() *RedeemRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the RedeemRuleUpdate builder.
func (_u *RedeemRuleUpdateOne) Where(ps ...predicate.RedeemRule) *RedeemRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemRuleUpdateOne) Select(field string, fields ...string) *RedeemRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemRule entity.
func (_u *RedeemRuleUpdateOne) Save(ctx context.Context) (*RedeemRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemRuleUpdateOne) SaveX(ctx context.Context) *RedeemRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RedeemRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := redeemrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemRuleUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := redeemrule.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "RedeemRule.type": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemRuleUpdateOne) sqlSave(ctx context.Context) (_node *RedeemRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemrule.Table, redeemrule.Columns, sqlgraph.NewFieldSpec(redeemrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemrule.FieldID)
		for _, f := range fields {
			if !redeemrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(redeemrule.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerValue(); ok {
		_spec.SetField(redeemrule.FieldTriggerValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTriggerValue(); ok {
		_spec.AddField(redeemrule.FieldTriggerValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTimesPerUser(); ok {
		_spec.SetField(redeemrule.FieldMaxTimesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTimesPerUser(); ok {
		_spec.AddField(redeemrule.FieldMaxTimesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FallbackValue(); ok {
		_spec.SetField(redeemrule.FieldFallbackValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFallbackValue(); ok {
		_spec.AddField(redeemrule.FieldFallbackValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(redeemrule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(redeemrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(redeemrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(redeemrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RedeemRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
