// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/redeemrule"
)

// RedeemRule is the model entity for the RedeemRule schema.
type RedeemRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 兑换码类型：balance/concurrency/subscription
	Type string `json:"type,omitempty"`
	// 触发金额，如 5.00
	TriggerValue float64 `json:"trigger_value,omitempty"`
	// 每用户可享受原价的次数
	MaxTimesPerUser int `json:"max_times_per_user,omitempty"`
	// 降级金额，如 2.00
	FallbackValue float64 `json:"fallback_value,omitempty"`
	// 规则是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 规则说明
	Description *string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedeemRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redeemrule.FieldIsActive:
			values[i] = new(sql.NullBool)
		case redeemrule.FieldTriggerValue, redeemrule.FieldFallbackValue:
			values[i] = new(sql.NullFloat64)
		case redeemrule.FieldID, redeemrule.FieldMaxTimesPerUser:
			values[i] = new(sql.NullInt64)
		case redeemrule.FieldType, redeemrule.FieldDescription:
			values[i] = new(sql.NullString)
		case redeemrule.FieldCreatedAt, redeemrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedeemRule fields.
func (_m *RedeemRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redeemrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case redeemrule.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case redeemrule.FieldTriggerValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_value", values[i])
			} else if value.Valid {
				_m.TriggerValue = value.Float64
			}
		case redeemrule.FieldMaxTimesPerUser:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_times_per_user", values[i])
			} else if value.Valid {
				_m.MaxTimesPerUser = int(value.Int64)
			}
		case redeemrule.FieldFallbackValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_value", values[i])
			} else if value.Valid {
				_m.FallbackValue = value.Float64
			}
		case redeemrule.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case redeemrule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case redeemrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case redeemrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedeemRule.
// This includes values selected through modifiers, order, etc.
func (_m *RedeemRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RedeemRule.
// Note that you need to call RedeemRule.Unwrap() before calling this method if this RedeemRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedeemRule) Update() *RedeemRuleUpdateOne {
	return NewRedeemRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedeemRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedeemRule) Unwrap() *RedeemRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedeemRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedeemRule) String() string {
	var builder strings.Builder
	builder.WriteString("RedeemRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("trigger_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerValue))
	builder.WriteString(", ")
	builder.WriteString("max_times_per_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTimesPerUser))
	builder.WriteString(", ")
	builder.WriteString("fallback_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.FallbackValue))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedeemRules is a parsable slice of RedeemRule.
type RedeemRules []*RedeemRule
