// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userredeemstat"
)

// UserRedeemStatCreate is the builder for creating a UserRedeemStat entity.
type UserRedeemStatCreate struct {
	config
	mutation *UserRedeemStatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserRedeemStatCreate) SetUserID(v int64) *UserRedeemStatCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRedeemType sets the "redeem_type" field.
func (_c *UserRedeemStatCreate) SetRedeemType(v string) *UserRedeemStatCreate {
	_c.mutation.SetRedeemType(v)
	return _c
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_c *UserRedeemStatCreate) SetNillableRedeemType(v *string) *UserRedeemStatCreate {
	if v != nil {
		_c.SetRedeemType(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *UserRedeemStatCreate) SetValue(v float64) *UserRedeemStatCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *UserRedeemStatCreate) SetUsedCount(v int) *UserRedeemStatCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *UserRedeemStatCreate) SetNillableUsedCount(v *int) *UserRedeemStatCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UserRedeemStatCreate) SetLastUsedAt(v time.Time) *UserRedeemStatCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UserRedeemStatCreate) SetNillableLastUsedAt(v *time.Time) *UserRedeemStatCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserRedeemStatCreate) SetCreatedAt(v time.Time) *UserRedeemStatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserRedeemStatCreate) SetNillableCreatedAt(v *time.Time) *UserRedeemStatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserRedeemStatCreate) SetUpdatedAt(v time.Time) *UserRedeemStatCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserRedeemStatCreate) SetNillableUpdatedAt(v *time.Time) *UserRedeemStatCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserRedeemStatCreate) SetUser(v *User) *UserRedeemStatCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserRedeemStatMutation object of the builder.
func (_c *UserRedeemStatCreate) Mutation() *UserRedeemStatMutation {
	return _c.mutation
}

// Save creates the UserRedeemStat in the database.
func (_c *UserRedeemStatCreate) Save(ctx context.Context) (*UserRedeemStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserRedeemStatCreate) SaveX(ctx context.Context) *UserRedeemStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRedeemStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRedeemStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserRedeemStatCreate) defaults() {
	if _, ok := _c.mutation.RedeemType(); !ok {
		v := userredeemstat.DefaultRedeemType
		_c.mutation.SetRedeemType(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := userredeemstat.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userredeemstat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userredeemstat.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserRedeemStatCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserRedeemStat.user_id"`)}
	}
	if _, ok := _c.mutation.RedeemType(); !ok {
		return &ValidationError{Name: "redeem_type", err: errors.New(`ent: missing required field "UserRedeemStat.redeem_type"`)}
	}
	if v, ok := _c.mutation.RedeemType(); ok {
		if err := userredeemstat.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "UserRedeemStat.redeem_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "UserRedeemStat.value"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`ent: missing required field "UserRedeemStat.used_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserRedeemStat.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserRedeemStat.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserRedeemStat.user"`)}
	}
	return nil
}

func (_c *UserRedeemStatCreate) sqlSave(ctx context.Context) (*UserRedeemStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserRedeemStatCreate) createSpec() (*UserRedeemStat, *sqlgraph.CreateSpec) {
	var (
		_node = &UserRedeemStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userredeemstat.Table, sqlgraph.NewFieldSpec(userredeemstat.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RedeemType(); ok {
		_spec.SetField(userredeemstat.FieldRedeemType, field.TypeString, value)
		_node.RedeemType = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(userredeemstat.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(userredeemstat.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(userredeemstat.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userredeemstat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userredeemstat.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userredeemstat.UserTable,
			Columns: []string{userredeemstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRedeemStat.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRedeemStatUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRedeemStatCreate) OnConflict(opts ...sql.ConflictOption) *UserRedeemStatUpsertOne {
	_c.conflict = opts
	return &UserRedeemStatUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRedeemStatCreate) OnConflictColumns(columns ...string) *UserRedeemStatUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRedeemStatUpsertOne{
		create: _c,
	}
}

type (
	// UserRedeemStatUpsertOne is the builder for "upsert"-ing
	//  one UserRedeemStat node.
	UserRedeemStatUpsertOne struct {
		create *UserRedeemStatCreate
	}

	// UserRedeemStatUpsert is the "OnConflict" setter.
	UserRedeemStatUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserRedeemStatUpsert) SetUserID(v int64) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateUserID() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldUserID)
	return u
}

// SetRedeemType sets the "redeem_type" field.
func (u *UserRedeemStatUpsert) SetRedeemType(v string) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldRedeemType, v)
	return u
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateRedeemType() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldRedeemType)
	return u
}

// SetValue sets the "value" field.
func (u *UserRedeemStatUpsert) SetValue(v float64) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateValue() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *UserRedeemStatUpsert) AddValue(v float64) *UserRedeemStatUpsert {
	u.Add(userredeemstat.FieldValue, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *UserRedeemStatUpsert) SetUsedCount(v int) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateUsedCount() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *UserRedeemStatUpsert) AddUsedCount(v int) *UserRedeemStatUpsert {
	u.Add(userredeemstat.FieldUsedCount, v)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserRedeemStatUpsert) SetLastUsedAt(v time.Time) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateLastUsedAt() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserRedeemStatUpsert) ClearLastUsedAt() *UserRedeemStatUpsert {
	u.SetNull(userredeemstat.FieldLastUsedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRedeemStatUpsert) SetUpdatedAt(v time.Time) *UserRedeemStatUpsert {
	u.Set(userredeemstat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsert) UpdateUpdatedAt() *UserRedeemStatUpsert {
	u.SetExcluded(userredeemstat.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRedeemStatUpsertOne) UpdateNewValues() *UserRedeemStatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userredeemstat.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserRedeemStatUpsertOne) Ignore() *UserRedeemStatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRedeemStatUpsertOne) DoNothing() *UserRedeemStatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRedeemStatCreate.OnConflict
// documentation for more info.
func (u *UserRedeemStatUpsertOne) Update(set func(*UserRedeemStatUpsert)) *UserRedeemStatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRedeemStatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRedeemStatUpsertOne) SetUserID(v int64) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateUserID() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *UserRedeemStatUpsertOne) SetRedeemType(v string) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateRedeemType() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateRedeemType()
	})
}

// SetValue sets the "value" field.
func (u *UserRedeemStatUpsertOne) SetValue(v float64) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *UserRedeemStatUpsertOne) AddValue(v float64) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateValue() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateValue()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *UserRedeemStatUpsertOne) SetUsedCount(v int) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *UserRedeemStatUpsertOne) AddUsedCount(v int) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateUsedCount() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUsedCount()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserRedeemStatUpsertOne) SetLastUsedAt(v time.Time) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateLastUsedAt() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserRedeemStatUpsertOne) ClearLastUsedAt() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRedeemStatUpsertOne) SetUpdatedAt(v time.Time) *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsertOne) UpdateUpdatedAt() *UserRedeemStatUpsertOne {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRedeemStatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRedeemStatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRedeemStatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserRedeemStatUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserRedeemStatUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserRedeemStatCreateBulk is the builder for creating many UserRedeemStat entities in bulk.
type UserRedeemStatCreateBulk struct {
	config
	err      error
	builders []*UserRedeemStatCreate
	conflict []sql.ConflictOption
}

// Save creates the UserRedeemStat entities in the database.
func (_c *UserRedeemStatCreateBulk) Save(ctx context.Context) ([]*UserRedeemStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserRedeemStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserRedeemStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserRedeemStatCreateBulk) SaveX(ctx context.Context) []*UserRedeemStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserRedeemStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserRedeemStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserRedeemStat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserRedeemStatUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserRedeemStatCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserRedeemStatUpsertBulk {
	_c.conflict = opts
	return &UserRedeemStatUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserRedeemStatCreateBulk) OnConflictColumns(columns ...string) *UserRedeemStatUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserRedeemStatUpsertBulk{
		create: _c,
	}
}

// UserRedeemStatUpsertBulk is the builder for "upsert"-ing
// a bulk of UserRedeemStat nodes.
type UserRedeemStatUpsertBulk struct {
	create *UserRedeemStatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserRedeemStatUpsertBulk) UpdateNewValues() *UserRedeemStatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userredeemstat.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserRedeemStat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserRedeemStatUpsertBulk) Ignore() *UserRedeemStatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserRedeemStatUpsertBulk) DoNothing() *UserRedeemStatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserRedeemStatCreateBulk.OnConflict
// documentation for more info.
func (u *UserRedeemStatUpsertBulk) Update(set func(*UserRedeemStatUpsert)) *UserRedeemStatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserRedeemStatUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserRedeemStatUpsertBulk) SetUserID(v int64) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateUserID() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *UserRedeemStatUpsertBulk) SetRedeemType(v string) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateRedeemType() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateRedeemType()
	})
}

// SetValue sets the "value" field.
func (u *UserRedeemStatUpsertBulk) SetValue(v float64) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *UserRedeemStatUpsertBulk) AddValue(v float64) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateValue() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateValue()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *UserRedeemStatUpsertBulk) SetUsedCount(v int) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *UserRedeemStatUpsertBulk) AddUsedCount(v int) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateUsedCount() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUsedCount()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *UserRedeemStatUpsertBulk) SetLastUsedAt(v time.Time) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateLastUsedAt() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *UserRedeemStatUpsertBulk) ClearLastUsedAt() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserRedeemStatUpsertBulk) SetUpdatedAt(v time.Time) *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserRedeemStatUpsertBulk) UpdateUpdatedAt() *UserRedeemStatUpsertBulk {
	return u.Update(func(s *UserRedeemStatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserRedeemStatUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserRedeemStatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserRedeemStatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserRedeemStatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
