// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userredeemstat"
)

// UserRedeemStatUpdate is the builder for updating UserRedeemStat entities.
type UserRedeemStatUpdate struct {
	config
	hooks    []Hook
	mutation *UserRedeemStatMutation
}

// Where appends a list predicates to the UserRedeemStatUpdate builder.
func (_u *UserRedeemStatUpdate) Where(ps ...predicate.UserRedeemStat) *UserRedeemStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRedeemStatUpdate) SetUserID(v int64) *UserRedeemStatUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRedeemStatUpdate) SetNillableUserID(v *int64) *UserRedeemStatUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *UserRedeemStatUpdate) SetRedeemType(v string) *UserRedeemStatUpdate {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *UserRedeemStatUpdate) SetNillableRedeemType(v *string) *UserRedeemStatUpdate {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *UserRedeemStatUpdate) SetValue(v float64) *UserRedeemStatUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *UserRedeemStatUpdate) SetNillableValue(v *float64) *UserRedeemStatUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *UserRedeemStatUpdate) AddValue(v float64) *UserRedeemStatUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *UserRedeemStatUpdate) SetUsedCount(v int) *UserRedeemStatUpdate {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *UserRedeemStatUpdate) SetNillableUsedCount(v *int) *UserRedeemStatUpdate {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *UserRedeemStatUpdate) AddUsedCount(v int) *UserRedeemStatUpdate {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserRedeemStatUpdate) SetLastUsedAt(v time.Time) *UserRedeemStatUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserRedeemStatUpdate) SetNillableLastUsedAt(v *time.Time) *UserRedeemStatUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserRedeemStatUpdate) ClearLastUsedAt() *UserRedeemStatUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRedeemStatUpdate) SetUpdatedAt(v time.Time) *UserRedeemStatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRedeemStatUpdate) SetUser(v *User) *UserRedeemStatUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRedeemStatMutation object of the builder.
func (_u *UserRedeemStatUpdate) Mutation() *UserRedeemStatMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRedeemStatUpdate) ClearUser() *UserRedeemStatUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRedeemStatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRedeemStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRedeemStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRedeemStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRedeemStatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userredeemstat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRedeemStatUpdate) check() error {
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := userredeemstat.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "UserRedeemStat.redeem_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRedeemStat.user"`)
	}
	return nil
}

func (_u *UserRedeemStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userredeemstat.Table, userredeemstat.Columns, sqlgraph.NewFieldSpec(userredeemstat.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(userredeemstat.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(userredeemstat.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(userredeemstat.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(userredeemstat.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(userredeemstat.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userredeemstat.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userredeemstat.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userredeemstat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userredeemstat.UserTable,
			Columns: []string{userredeemstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userredeemstat.UserTable,
			Columns: []string{userredeemstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userredeemstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRedeemStatUpdateOne is the builder for updating a single UserRedeemStat entity.
type UserRedeemStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRedeemStatMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserRedeemStatUpdateOne) SetUserID(v int64) *UserRedeemStatUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRedeemStatUpdateOne) SetNillableUserID(v *int64) *UserRedeemStatUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *UserRedeemStatUpdateOne) SetRedeemType(v string) *UserRedeemStatUpdateOne {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *UserRedeemStatUpdateOne) SetNillableRedeemType(v *string) *UserRedeemStatUpdateOne {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *UserRedeemStatUpdateOne) SetValue(v float64) *UserRedeemStatUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *UserRedeemStatUpdateOne) SetNillableValue(v *float64) *UserRedeemStatUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *UserRedeemStatUpdateOne) AddValue(v float64) *UserRedeemStatUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetUsedCount sets the "used_count" field.
func (_u *UserRedeemStatUpdateOne) SetUsedCount(v int) *UserRedeemStatUpdateOne {
	_u.mutation.ResetUsedCount()
	_u.mutation.SetUsedCount(v)
	return _u
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_u *UserRedeemStatUpdateOne) SetNillableUsedCount(v *int) *UserRedeemStatUpdateOne {
	if v != nil {
		_u.SetUsedCount(*v)
	}
	return _u
}

// AddUsedCount adds value to the "used_count" field.
func (_u *UserRedeemStatUpdateOne) AddUsedCount(v int) *UserRedeemStatUpdateOne {
	_u.mutation.AddUsedCount(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserRedeemStatUpdateOne) SetLastUsedAt(v time.Time) *UserRedeemStatUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserRedeemStatUpdateOne) SetNillableLastUsedAt(v *time.Time) *UserRedeemStatUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserRedeemStatUpdateOne) ClearLastUsedAt() *UserRedeemStatUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserRedeemStatUpdateOne) SetUpdatedAt(v time.Time) *UserRedeemStatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRedeemStatUpdateOne) SetUser(v *User) *UserRedeemStatUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserRedeemStatMutation object of the builder.
func (_u *UserRedeemStatUpdateOne) Mutation() *UserRedeemStatMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRedeemStatUpdateOne) ClearUser() *UserRedeemStatUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserRedeemStatUpdate builder.
func (_u *UserRedeemStatUpdateOne) Where(ps ...predicate.UserRedeemStat) *UserRedeemStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRedeemStatUpdateOne) Select(field string, fields ...string) *UserRedeemStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRedeemStat entity.
func (_u *UserRedeemStatUpdateOne) Save(ctx context.Context) (*UserRedeemStat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRedeemStatUpdateOne) SaveX(ctx context.Context) *UserRedeemStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRedeemStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRedeemStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserRedeemStatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userredeemstat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRedeemStatUpdateOne) check() error {
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := userredeemstat.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "UserRedeemStat.redeem_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRedeemStat.user"`)
	}
	return nil
}

func (_u *UserRedeemStatUpdateOne) sqlSave(ctx context.Context) (_node *UserRedeemStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userredeemstat.Table, userredeemstat.Columns, sqlgraph.NewFieldSpec(userredeemstat.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRedeemStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userredeemstat.FieldID)
		for _, f := range fields {
			if !userredeemstat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userredeemstat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(userredeemstat.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(userredeemstat.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(userredeemstat.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedCount(); ok {
		_spec.SetField(userredeemstat.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsedCount(); ok {
		_spec.AddField(userredeemstat.FieldUsedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userredeemstat.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userredeemstat.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userredeemstat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userredeemstat.UserTable,
			Columns: []string{userredeemstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userredeemstat.UserTable,
			Columns: []string{userredeemstat.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRedeemStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userredeemstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
