// Code generated by ent, DO NOT EDIT.

package userredeemstat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUserID, v))
}

// RedeemType applies equality check predicate on the "redeem_type" field. It's identical to RedeemTypeEQ.
func RedeemType(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldRedeemType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldValue, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUsedCount, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldLastUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldUserID, vs...))
}

// RedeemTypeEQ applies the EQ predicate on the "redeem_type" field.
func RedeemTypeEQ(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldRedeemType, v))
}

// RedeemTypeNEQ applies the NEQ predicate on the "redeem_type" field.
func RedeemTypeNEQ(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldRedeemType, v))
}

// RedeemTypeIn applies the In predicate on the "redeem_type" field.
func RedeemTypeIn(vs ...string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldRedeemType, vs...))
}

// RedeemTypeNotIn applies the NotIn predicate on the "redeem_type" field.
func RedeemTypeNotIn(vs ...string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldRedeemType, vs...))
}

// RedeemTypeGT applies the GT predicate on the "redeem_type" field.
func RedeemTypeGT(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldRedeemType, v))
}

// RedeemTypeGTE applies the GTE predicate on the "redeem_type" field.
func RedeemTypeGTE(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldRedeemType, v))
}

// RedeemTypeLT applies the LT predicate on the "redeem_type" field.
func RedeemTypeLT(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldRedeemType, v))
}

// RedeemTypeLTE applies the LTE predicate on the "redeem_type" field.
func RedeemTypeLTE(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldRedeemType, v))
}

// RedeemTypeContains applies the Contains predicate on the "redeem_type" field.
func RedeemTypeContains(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldContains(FieldRedeemType, v))
}

// RedeemTypeHasPrefix applies the HasPrefix predicate on the "redeem_type" field.
func RedeemTypeHasPrefix(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldHasPrefix(FieldRedeemType, v))
}

// RedeemTypeHasSuffix applies the HasSuffix predicate on the "redeem_type" field.
func RedeemTypeHasSuffix(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldHasSuffix(FieldRedeemType, v))
}

// RedeemTypeEqualFold applies the EqualFold predicate on the "redeem_type" field.
func RedeemTypeEqualFold(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEqualFold(FieldRedeemType, v))
}

// RedeemTypeContainsFold applies the ContainsFold predicate on the "redeem_type" field.
func RedeemTypeContainsFold(v string) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldContainsFold(FieldRedeemType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v float64) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldValue, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldUsedCount, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotNull(FieldLastUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserRedeemStat {
	return predicate.UserRedeemStat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRedeemStat) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRedeemStat) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRedeemStat) predicate.UserRedeemStat {
	return predicate.UserRedeemStat(sql.NotPredicates(p))
}
