// Code generated by ent, DO NOT EDIT.

package redeemrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the redeemrule type in the database.
	Label = "redeem_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTriggerValue holds the string denoting the trigger_value field in the database.
	FieldTriggerValue = "trigger_value"
	// FieldMaxTimesPerUser holds the string denoting the max_times_per_user field in the database.
	FieldMaxTimesPerUser = "max_times_per_user"
	// FieldFallbackValue holds the string denoting the fallback_value field in the database.
	FieldFallbackValue = "fallback_value"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the redeemrule in the database.
	Table = "redeem_rules"
)

// Columns holds all SQL columns for redeemrule fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldTriggerValue,
	FieldMaxTimesPerUser,
	FieldFallbackValue,
	FieldIsActive,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultMaxTimesPerUser holds the default value on creation for the "max_times_per_user" field.
	DefaultMaxTimesPerUser int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RedeemRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByTriggerValue orders the results by the trigger_value field.
func ByTriggerValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerValue, opts...).ToFunc()
}

// ByMaxTimesPerUser orders the results by the max_times_per_user field.
func ByMaxTimesPerUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTimesPerUser, opts...).ToFunc()
}

// ByFallbackValue orders the results by the fallback_value field.
func ByFallbackValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFallbackValue, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
