// Code generated by ent, DO NOT EDIT.

package redeemrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldType, v))
}

// TriggerValue applies equality check predicate on the "trigger_value" field. It's identical to TriggerValueEQ.
func TriggerValue(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldTriggerValue, v))
}

// MaxTimesPerUser applies equality check predicate on the "max_times_per_user" field. It's identical to MaxTimesPerUserEQ.
func MaxTimesPerUser(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldMaxTimesPerUser, v))
}

// FallbackValue applies equality check predicate on the "fallback_value" field. It's identical to FallbackValueEQ.
func FallbackValue(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldFallbackValue, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldIsActive, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldContainsFold(FieldType, v))
}

// TriggerValueEQ applies the EQ predicate on the "trigger_value" field.
func TriggerValueEQ(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldTriggerValue, v))
}

// TriggerValueNEQ applies the NEQ predicate on the "trigger_value" field.
func TriggerValueNEQ(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldTriggerValue, v))
}

// TriggerValueIn applies the In predicate on the "trigger_value" field.
func TriggerValueIn(vs ...float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldTriggerValue, vs...))
}

// TriggerValueNotIn applies the NotIn predicate on the "trigger_value" field.
func TriggerValueNotIn(vs ...float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldTriggerValue, vs...))
}

// TriggerValueGT applies the GT predicate on the "trigger_value" field.
func TriggerValueGT(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldTriggerValue, v))
}

// TriggerValueGTE applies the GTE predicate on the "trigger_value" field.
func TriggerValueGTE(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldTriggerValue, v))
}

// TriggerValueLT applies the LT predicate on the "trigger_value" field.
func TriggerValueLT(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldTriggerValue, v))
}

// TriggerValueLTE applies the LTE predicate on the "trigger_value" field.
func TriggerValueLTE(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldTriggerValue, v))
}

// MaxTimesPerUserEQ applies the EQ predicate on the "max_times_per_user" field.
func MaxTimesPerUserEQ(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldMaxTimesPerUser, v))
}

// MaxTimesPerUserNEQ applies the NEQ predicate on the "max_times_per_user" field.
func MaxTimesPerUserNEQ(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldMaxTimesPerUser, v))
}

// MaxTimesPerUserIn applies the In predicate on the "max_times_per_user" field.
func MaxTimesPerUserIn(vs ...int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldMaxTimesPerUser, vs...))
}

// MaxTimesPerUserNotIn applies the NotIn predicate on the "max_times_per_user" field.
func MaxTimesPerUserNotIn(vs ...int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldMaxTimesPerUser, vs...))
}

// MaxTimesPerUserGT applies the GT predicate on the "max_times_per_user" field.
func MaxTimesPerUserGT(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldMaxTimesPerUser, v))
}

// MaxTimesPerUserGTE applies the GTE predicate on the "max_times_per_user" field.
func MaxTimesPerUserGTE(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldMaxTimesPerUser, v))
}

// MaxTimesPerUserLT applies the LT predicate on the "max_times_per_user" field.
func MaxTimesPerUserLT(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldMaxTimesPerUser, v))
}

// MaxTimesPerUserLTE applies the LTE predicate on the "max_times_per_user" field.
func MaxTimesPerUserLTE(v int) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldMaxTimesPerUser, v))
}

// FallbackValueEQ applies the EQ predicate on the "fallback_value" field.
func FallbackValueEQ(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldFallbackValue, v))
}

// FallbackValueNEQ applies the NEQ predicate on the "fallback_value" field.
func FallbackValueNEQ(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldFallbackValue, v))
}

// FallbackValueIn applies the In predicate on the "fallback_value" field.
func FallbackValueIn(vs ...float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldFallbackValue, vs...))
}

// FallbackValueNotIn applies the NotIn predicate on the "fallback_value" field.
func FallbackValueNotIn(vs ...float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldFallbackValue, vs...))
}

// FallbackValueGT applies the GT predicate on the "fallback_value" field.
func FallbackValueGT(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldFallbackValue, v))
}

// FallbackValueGTE applies the GTE predicate on the "fallback_value" field.
func FallbackValueGTE(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldFallbackValue, v))
}

// FallbackValueLT applies the LT predicate on the "fallback_value" field.
func FallbackValueLT(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldFallbackValue, v))
}

// FallbackValueLTE applies the LTE predicate on the "fallback_value" field.
func FallbackValueLTE(v float64) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldFallbackValue, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldIsActive, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RedeemRule {
	return predicate.RedeemRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemRule) predicate.RedeemRule {
	return predicate.RedeemRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemRule) predicate.RedeemRule {
	return predicate.RedeemRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemRule) predicate.RedeemRule {
	return predicate.RedeemRule(sql.NotPredicates(p))
}
