// Code generated by ent, DO NOT EDIT.

package balancesnapshotdaily

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the balancesnapshotdaily type in the database.
	Label = "balance_snapshot_daily"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSnapshotDate holds the string denoting the snapshot_date field in the database.
	FieldSnapshotDate = "snapshot_date"
	// FieldTotalBalance holds the string denoting the total_balance field in the database.
	FieldTotalBalance = "total_balance"
	// FieldUserCount holds the string denoting the user_count field in the database.
	FieldUserCount = "user_count"
	// FieldComputedAt holds the string denoting the computed_at field in the database.
	FieldComputedAt = "computed_at"
	// Table holds the table name of the balancesnapshotdaily in the database.
	Table = "balance_snapshots_daily"
)

// Columns holds all SQL columns for balancesnapshotdaily fields.
var Columns = []string{
	FieldID,
	FieldSnapshotDate,
	FieldTotalBalance,
	FieldUserCount,
	FieldComputedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalBalance holds the default value on creation for the "total_balance" field.
	DefaultTotalBalance float64
	// DefaultUserCount holds the default value on creation for the "user_count" field.
	DefaultUserCount int64
	// DefaultComputedAt holds the default value on creation for the "computed_at" field.
	DefaultComputedAt func() time.Time
)

// OrderOption defines the ordering options for the BalanceSnapshotDaily queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySnapshotDate orders the results by the snapshot_date field.
func BySnapshotDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotDate, opts...).ToFunc()
}

// ByTotalBalance orders the results by the total_balance field.
func ByTotalBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalBalance, opts...).ToFunc()
}

// ByUserCount orders the results by the user_count field.
func ByUserCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserCount, opts...).ToFunc()
}

// ByComputedAt orders the results by the computed_at field.
func ByComputedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComputedAt, opts...).ToFunc()
}
