// Code generated by ent, DO NOT EDIT.

package balancesnapshotdaily

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLTE(FieldID, id))
}

// SnapshotDate applies equality check predicate on the "snapshot_date" field. It's identical to SnapshotDateEQ.
func SnapshotDate(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldSnapshotDate, v))
}

// TotalBalance applies equality check predicate on the "total_balance" field. It's identical to TotalBalanceEQ.
func TotalBalance(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldTotalBalance, v))
}

// UserCount applies equality check predicate on the "user_count" field. It's identical to UserCountEQ.
func UserCount(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldUserCount, v))
}

// ComputedAt applies equality check predicate on the "computed_at" field. It's identical to ComputedAtEQ.
func ComputedAt(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldComputedAt, v))
}

// SnapshotDateEQ applies the EQ predicate on the "snapshot_date" field.
func SnapshotDateEQ(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldSnapshotDate, v))
}

// SnapshotDateNEQ applies the NEQ predicate on the "snapshot_date" field.
func SnapshotDateNEQ(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNEQ(FieldSnapshotDate, v))
}

// SnapshotDateIn applies the In predicate on the "snapshot_date" field.
func SnapshotDateIn(vs ...time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldIn(FieldSnapshotDate, vs...))
}

// SnapshotDateNotIn applies the NotIn predicate on the "snapshot_date" field.
func SnapshotDateNotIn(vs ...time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNotIn(FieldSnapshotDate, vs...))
}

// SnapshotDateGT applies the GT predicate on the "snapshot_date" field.
func SnapshotDateGT(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGT(FieldSnapshotDate, v))
}

// SnapshotDateGTE applies the GTE predicate on the "snapshot_date" field.
func SnapshotDateGTE(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGTE(FieldSnapshotDate, v))
}

// SnapshotDateLT applies the LT predicate on the "snapshot_date" field.
func SnapshotDateLT(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLT(FieldSnapshotDate, v))
}

// SnapshotDateLTE applies the LTE predicate on the "snapshot_date" field.
func SnapshotDateLTE(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLTE(FieldSnapshotDate, v))
}

// TotalBalanceEQ applies the EQ predicate on the "total_balance" field.
func TotalBalanceEQ(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldTotalBalance, v))
}

// TotalBalanceNEQ applies the NEQ predicate on the "total_balance" field.
func TotalBalanceNEQ(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNEQ(FieldTotalBalance, v))
}

// TotalBalanceIn applies the In predicate on the "total_balance" field.
func TotalBalanceIn(vs ...float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldIn(FieldTotalBalance, vs...))
}

// TotalBalanceNotIn applies the NotIn predicate on the "total_balance" field.
func TotalBalanceNotIn(vs ...float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNotIn(FieldTotalBalance, vs...))
}

// TotalBalanceGT applies the GT predicate on the "total_balance" field.
func TotalBalanceGT(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGT(FieldTotalBalance, v))
}

// TotalBalanceGTE applies the GTE predicate on the "total_balance" field.
func TotalBalanceGTE(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGTE(FieldTotalBalance, v))
}

// TotalBalanceLT applies the LT predicate on the "total_balance" field.
func TotalBalanceLT(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLT(FieldTotalBalance, v))
}

// TotalBalanceLTE applies the LTE predicate on the "total_balance" field.
func TotalBalanceLTE(v float64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLTE(FieldTotalBalance, v))
}

// UserCountEQ applies the EQ predicate on the "user_count" field.
func UserCountEQ(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldUserCount, v))
}

// UserCountNEQ applies the NEQ predicate on the "user_count" field.
func UserCountNEQ(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNEQ(FieldUserCount, v))
}

// UserCountIn applies the In predicate on the "user_count" field.
func UserCountIn(vs ...int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldIn(FieldUserCount, vs...))
}

// UserCountNotIn applies the NotIn predicate on the "user_count" field.
func UserCountNotIn(vs ...int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNotIn(FieldUserCount, vs...))
}

// UserCountGT applies the GT predicate on the "user_count" field.
func UserCountGT(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGT(FieldUserCount, v))
}

// UserCountGTE applies the GTE predicate on the "user_count" field.
func UserCountGTE(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGTE(FieldUserCount, v))
}

// UserCountLT applies the LT predicate on the "user_count" field.
func UserCountLT(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLT(FieldUserCount, v))
}

// UserCountLTE applies the LTE predicate on the "user_count" field.
func UserCountLTE(v int64) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLTE(FieldUserCount, v))
}

// ComputedAtEQ applies the EQ predicate on the "computed_at" field.
func ComputedAtEQ(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldEQ(FieldComputedAt, v))
}

// ComputedAtNEQ applies the NEQ predicate on the "computed_at" field.
func ComputedAtNEQ(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNEQ(FieldComputedAt, v))
}

// ComputedAtIn applies the In predicate on the "computed_at" field.
func ComputedAtIn(vs ...time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldIn(FieldComputedAt, vs...))
}

// ComputedAtNotIn applies the NotIn predicate on the "computed_at" field.
func ComputedAtNotIn(vs ...time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldNotIn(FieldComputedAt, vs...))
}

// ComputedAtGT applies the GT predicate on the "computed_at" field.
func ComputedAtGT(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGT(FieldComputedAt, v))
}

// ComputedAtGTE applies the GTE predicate on the "computed_at" field.
func ComputedAtGTE(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldGTE(FieldComputedAt, v))
}

// ComputedAtLT applies the LT predicate on the "computed_at" field.
func ComputedAtLT(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLT(FieldComputedAt, v))
}

// ComputedAtLTE applies the LTE predicate on the "computed_at" field.
func ComputedAtLTE(v time.Time) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.FieldLTE(FieldComputedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceSnapshotDaily) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceSnapshotDaily) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceSnapshotDaily) predicate.BalanceSnapshotDaily {
	return predicate.BalanceSnapshotDaily(sql.NotPredicates(p))
}
